#!/usr/bin/env python
"""
run_inject_v3.py -- inject Bonnor-Ebert sphere models into Herschel maps.

DO NOT EDIT THIS FILE.  All settings live in a config file.

WHAT CHANGED IN VERSION 3
-------------------------
Version 3 rebuilds the way a model is matched to a place in the map.  Four
independent defects of version 2 are corrected; each is documented in full at
the point where it is fixed, and each is summarised here.

1. The embedding window is now symmetric.  The rungs of the model grid in
   embedding column SD_emb are spaced by a factor of 2, but version 2 allowed
   a model to be placed only where the local column lay in
   [SD_emb, sqrt(2)*SD_emb), a window half a rung wide.  The upper half of
   every octave therefore belonged to no model.  Of the 1030 real Aquila
   sources, 520 sit at columns inside those gaps, and so does the median
   column of the population, 5.04e21 cm^-2.  Models drawn for such columns
   fell through to a nearest-rung fallback that always selected the rung
   above, and were then placed at columns higher than the ones drawn.  This
   was the main cause of the injected sample being displaced toward high
   column density.  See inject.valid_placement_mask.

2. Models are selected and separated by their observed size, not by R_BE.
   The truncation radius R_BE is not an observable: grid nodes with R_BE
   between 136 and 428 arcsec present a surface-density half-maximum width
   FWHMSDbs of only 25 to 50 arcsec, well inside the range of the real
   sources.  Cutting on R_BE discarded every node above 1.8 solar masses and
   gave the surviving models exclusion zones far larger than their apparent
   extent, which is why a few large faint models consumed the usable area.
   FWHM_MIN_AS and FWHM_MAX_AS replace R_BE_MIN_AS and R_BE_MAX_AS.

3. The mass match is made against the model's own reported SED mass,
   M_SED4bs, rather than against its true mass M_BE.  The target masses are
   reported SED masses of real sources, and over the eligible nodes the ratio
   M_BE / M_SED4bs has median 1.105, so matching against M_BE built in a
   systematic offset of 0.043 in base-10 logarithm.

4. Real-source footprints are avoided by the core center only, with a fixed
   margin, instead of by the whole R_BE disk.  The footprints cover 6.5% of
   the sub-field; eroding by an R_BE of 70 arcsec turned that into most of
   the field, which is why avoidance had been switched off altogether.

The target distribution itself is now built by build_joint_target_v3.py and
carries a fourth column, the observed size of each real source.

USAGE
-----
  python -B run_inject.py                        # uses inject_config.py
  python -B run_inject.py inject_config_set3     # uses inject_config_set3.py
  python -B run_inject.py inject_config_i1j2k4   # single-model config

CONFIG FILE FORMATS
-------------------
Multi-model (preferred for Tier-2):
  SET_TAG = 'set3'
  MODELS  = [ dict(tag=..., sd_emb=..., r_be_arcsec=..., stamp_files={...}), ... ]
  Separation computed automatically: sqrt((2*R_BE_max)^2 + 36.3^2).

Single-model (backward compatible):
  MODEL_TAG, SD_EMB, R_BE_ARCSEC, STAMP_FILES, MIN_SEP_ARCSEC

Both formats share field paths via inject_config_field.py (on PYTHONPATH
or in the same directory as this script / its Python/ subdirectory).

DEPENDENCIES
------------
  pip install numpy astropy scipy
"""

import sys, os, importlib, importlib.util
import math
import numpy as np
from astropy.io import fits

# -----------------------------------------------------------------------
# Search order: cwd -> script/Python/ -> script dir -> PYTHONPATH
# -----------------------------------------------------------------------
_here    = os.path.dirname(os.path.abspath(__file__))
_here_py = os.path.join(_here, 'Python')
_cwd     = os.getcwd()
sys.path.insert(0, _here)
sys.path.insert(0, _here_py)
sys.path.insert(0, _cwd)

try:
    from fit_mass import load_catalog as _load_grid
except ModuleNotFoundError:
    raise ModuleNotFoundError(
        'fit_mass.py not found. Place it in SCRIPTS/Python/ alongside inject.py.')

def _find_catalog(name):
    """Search for catalog file in cwd, then script Python/ dir, then script dir."""
    for d in [_cwd, _here_py, _here]:
        p = os.path.join(d, name)
        if os.path.exists(p):
            return p
    raise FileNotFoundError(
        f'"{name}" not found in cwd, {_here_py}, or {_here}.\n'
        f'Set BES_CATALOG in inject_config_field.py or place the file in SCRIPTS/Python/')

_config_arg  = sys.argv[1] if len(sys.argv) > 1 else 'inject_config'
_config_name = os.path.splitext(os.path.basename(_config_arg))[0]
_config_file = os.path.join(_cwd, _config_name + '.py')

if not os.path.exists(_config_file):
    print(f'ERROR: config file "{_config_name}.py" not found in:')
    print(f'  {_cwd}')
    print(f'  Config files must have the .py extension.')
    print(f'  If your file has no extension, rename it:')
    print(f'    mv {_config_name} {_config_name}.py')
    sys.exit(1)

try:
    _spec = importlib.util.spec_from_file_location(_config_name, _config_file)
    _cfg  = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_cfg)
except Exception as _e:
    print(f'ERROR: failed to load "{_config_name}.py": {_e}')
    print(f'  helper modules searched in: {_here_py}  and  {_here}')
    sys.exit(1)

print(f'Config: {_config_name}  ({_config_file})')

import inject

# run_inject_v3.py requires the version-3 inject.py, in which
# valid_placement_mask takes the symmetric embedding window and the
# centre-only footprint margin.  An older inject.py left over in the run
# directory would otherwise fail deep inside main(), after the models have
# been selected and the stamps loaded, with an unexpected-keyword TypeError.
import inspect as _inspect
_need = {'window', 'forbid_margin_as', 'local_average_radius_as'}
_have = set(_inspect.signature(inject.valid_placement_mask).parameters)
if not _need <= _have:
    print('ERROR: the inject.py found alongside run_inject_v3.py is an older')
    print('       version.  inject.valid_placement_mask lacks: %s'
          % ', '.join(sorted(_need - _have)))
    print('       found at: %s' % os.path.abspath(inject.__file__))
    print('       Copy the version-3 inject.py into that directory.  Without')
    print('       it the embedding window would stay one-sided, which leaves')
    print('       half of every column octave unreachable.')
    sys.exit(1)

# load model grid catalog -- path set via BES_CATALOG in the config file;
# falls back to searching cwd and SCRIPTS/Python/ if not set.
_bes_catalog_path = getattr(_cfg, 'BES_CATALOG', None) or _find_catalog('bes_model_grid_final2_catalog')
_GRID = _load_grid(_bes_catalog_path)
print(f'Grid catalog: {_bes_catalog_path}')

# -----------------------------------------------------------------------
# Normalise config: support both single-model and multi-model formats
# -----------------------------------------------------------------------
BEAM500 = 36.3   # arcsec, 500um beam -- used for separation criterion


STAMP_J_PREFIX = 'M_'   # middle level of the stamp tree; was 'tBE_'


def _stamp_files_from_tag(tag, root):
    """Build stamp_files dict and surfdens_stamp path from a model tag and
    STAMP_ROOT, using the directory tree:
        <root>/cSD_{i:02d}/{STAMP_J_PREFIX}{j:02d}/{k:02d}/nc.<band>um.<suffix>.<res>x0.rs3p0as.fits
    where <suffix> is STAMP_SUFFIX, 'bsl' by default.
    STAMP_J_PREFIX defaults to 'M_' (formerly 'tBE_') and may be
    overridden in the config file.

    Band beam tokens (fixed Herschel PSF):
        160 um -> r13p5,  250 um -> r18p2,
        350 um -> r24p9,  500 um -> r36p3
    070 um is always None.  surfdens uses the 160 um token (r13p5).
    """
    import re
    m = re.fullmatch(r'i(\d+)j(\d+)k(\d+)', tag)
    if m is None:
        raise ValueError(f'Cannot parse model tag "{tag}": expected iNjMkK')
    i, j, k = int(m.group(1)), int(m.group(2)), int(m.group(3))
    subdir = os.path.join(root, f'cSD_{i:02d}', f'{STAMP_J_PREFIX}{j:02d}', f'{k:02d}')
    res = {'000': 'r13p5', '160': 'r13p5', '250': 'r18p2', '350': 'r24p9', '500': 'r36p3'}
    stamp_files = {'070': None}
    for b, r in res.items():
        if b == '000':
            stamp_files[b] = os.path.join(
                subdir, f'nc.surfdens.{STAMP_SUFFIX}.r13p5x0.rs3p0as.fits')
        else:
            stamp_files[b] = os.path.join(
                subdir, f'nc.{b}um.{STAMP_SUFFIX}.{r}x0.rs3p0as.fits')
    return stamp_files


def _normalise_model_entry(entry, stamp_root):
    """Accept a model entry as a bare tag string, a tag-only dict, or a full
    dict with stamp_files.  In the first two cases stamp paths are built
    automatically from STAMP_ROOT; a full dict is returned unchanged."""
    if isinstance(entry, str):
        entry = dict(tag=entry)
    if 'stamp_files' not in entry:
        if stamp_root is None:
            raise ValueError(
                f'Model "{entry["tag"]}" has no stamp_files and STAMP_ROOT is not set.')
        sf = _stamp_files_from_tag(entry['tag'], stamp_root)
        entry = dict(entry)
        entry['stamp_files'] = sf
    return entry

# A configuration that samples the core mass function does not name any model:
# the list is built later by _models_from_population.  Such a configuration
# therefore has neither MODELS nor the single-model keys MODEL_TAG, SD_EMB,
# R_BE_ARCSEC and STAMP_FILES, and before version 3 it had to carry the latter
# as dead entries to get past this branch.  Sampling the mass function is now
# recognised in its own right.
_CMF_MODE = (getattr(_cfg, 'CMF_SLOPE', None) is not None
             and getattr(_cfg, 'CMF_N_CORES', None))
if hasattr(_cfg, 'MODELS') or _CMF_MODE:
    # --- multi-model format ---
    SET_TAG  = getattr(_cfg, 'SET_TAG', None) or getattr(_cfg, 'MODEL_TAG', 'inj')
    STAMP_ROOT = getattr(_cfg, 'STAMP_ROOT', None)
    MODELS     = [_normalise_model_entry(m, STAMP_ROOT)
                  for m in getattr(_cfg, 'MODELS', [])]
    N_CORES  = getattr(_cfg, 'N_CORES', 5)
    RANDOM_SEED     = _cfg.RANDOM_SEED
    OUT_DIR         = _cfg.OUT_DIR
    IMG_PATHS       = _cfg.IMG_PATHS
    OMASK_PATHS     = _cfg.OMASK_PATHS
    SIGMA_PATH      = _cfg.SIGMA_PATH
    SIGMA_OMASK_PATH= _cfg.SIGMA_OMASK_PATH
    FOOTS_PATH      = _cfg.FOOTS_PATH
    HIRES_SURFDENS_PATH = getattr(_cfg, 'HIRES_SURFDENS_PATH', None)
    SCALE_FACTOR        = getattr(_cfg, 'SCALE_FACTOR', 1.0)
    R_BE_MAX_AS         = getattr(_cfg, 'R_BE_MAX_AS', None)  # skip models with R_BE > this (arcsec)
    if SCALE_FACTOR != 1.0: SET_TAG = SET_TAG + f'_x{SCALE_FACTOR:.4g}'
    # Treat surfdens as band '000': plug into IMG_PATHS/OMASK_PATHS so all
    # band loops handle it uniformly.
    if HIRES_SURFDENS_PATH:
        IMG_PATHS['000']   = HIRES_SURFDENS_PATH
        OMASK_PATHS['000'] = SIGMA_OMASK_PATH
    # MIN_SEP_ARCSEC computed in main() after r_be_arcsec is filled from grid
    MIN_SEP_ARCSEC = None
    if _CMF_MODE and not MODELS:
        print(f'  Set "{SET_TAG}": models to be drawn from the core mass '
              f'function ({_cfg.CMF_N_CORES} cores)')
    else:
        print(f'  Multi-model set "{SET_TAG}": {len(MODELS)} models')
else:
    # --- single-model format (backward compatible) ---
    SET_TAG  = _cfg.MODEL_TAG
    MODELS   = [dict(
        tag         = _cfg.MODEL_TAG,
        sd_emb      = _cfg.SD_EMB,
        r_be_arcsec = _cfg.R_BE_ARCSEC,
        stamp_files = _cfg.STAMP_FILES,
        surfdens_stamp = None,
    )]
    N_CORES          = _cfg.N_CORES
    MIN_SEP_ARCSEC   = _cfg.MIN_SEP_ARCSEC
    RANDOM_SEED      = _cfg.RANDOM_SEED
    OUT_DIR          = _cfg.OUT_DIR
    IMG_PATHS        = _cfg.IMG_PATHS
    OMASK_PATHS      = _cfg.OMASK_PATHS
    SIGMA_PATH       = _cfg.SIGMA_PATH
    SIGMA_OMASK_PATH = _cfg.SIGMA_OMASK_PATH
    FOOTS_PATH       = _cfg.FOOTS_PATH
    HIRES_SURFDENS_PATH = getattr(_cfg, 'HIRES_SURFDENS_PATH', None)
    SCALE_FACTOR        = getattr(_cfg, 'SCALE_FACTOR', 1.0)
    if SCALE_FACTOR != 1.0: SET_TAG = SET_TAG + f'_x{SCALE_FACTOR:.4g}'
    if HIRES_SURFDENS_PATH:
        IMG_PATHS['000']   = HIRES_SURFDENS_PATH
        OMASK_PATHS['000'] = SIGMA_OMASK_PATH
    print(f'  Single-model: {SET_TAG}')
# Everything the v2 setup prints is mirrored here and written into the header
# of the truth table, so that a realisation documents the sampling that
# produced it.
_V2_LOG = []


def _vprint(msg):
    print(msg)
    _V2_LOG.append(msg)


# --- v2 options -----------------------------------------------------------
# These are read from the config file, NOT from the environment.  Add them to
# inject_config.py; omit them and run_inject_v2.py behaves exactly as v1.
#
#   CMF_SLOPE = 2.0            # dN/dM ~ M^-alpha; alpha = x + 1, so x = 1.0
#   CMF_N_CORES = 500          # number of cores to draw
#   CMF_MASS_RANGE = (0.05, 20.0)   # solar masses
#   SIGMA_TARGET_FILE = 'sigma_target_Aquila.txt'
#   FLATTEN_BACKGROUND = False
#
# Defined here, after both the multi-model and single-model config branches, so
# that they exist whichever format the config file uses.
STAMP_ROOT         = globals().get('STAMP_ROOT', getattr(_cfg, 'STAMP_ROOT', None))
CMF_SLOPE          = getattr(_cfg, 'CMF_SLOPE', None)
CMF_MASS_RANGE     = getattr(_cfg, 'CMF_MASS_RANGE', (0.05, 20.0))
CMF_N_CORES        = getattr(_cfg, 'CMF_N_CORES', None)
SIGMA_TARGET_FILE  = getattr(_cfg, 'SIGMA_TARGET_FILE', None)
# CONTRAST_TARGET_FILE holds one value per line of the getsf source contrast,
# PEAK_SBF / PEAK_BGF = (source + background) / background, which exceeds unity,
# measured for real sources in the field being imitated.  When given, models are chosen
# to reproduce that distribution of contrast rather than only the distribution
# of background column: matching the background alone does not match the
# contrast, because the contrast also depends on the model's own peak.  In the
# first core-mass-function injection the injected cores had a median contrast of
# 1.731 against 1.235 for real Aquila sources, so their source component was
# three times too prominent relative to the background.
CONTRAST_TARGET_FILE = getattr(_cfg, 'CONTRAST_TARGET_FILE', None)
# FWHM_MIN_AS and FWHM_MAX_AS restrict the grid nodes by their observed size,
# the model column FWHMSDbs, which is the major axis at half maximum in the
# surface-density image.  This replaces R_BE_MIN_AS and R_BE_MAX_AS.
#
# The lower limit exists because a core narrower than the 13.5 arcsec
# surface-density beam cannot be measured: in the first injection the recovered
# mass of such cores scattered by a factor of 8.8 and was biased high by up to
# a factor of 260, because the beam measures the surrounding cloud rather than
# the core.  The upper limit exists because the injected cores should look like
# real ones; over the 1030 real Aquila sources, AFWHM in the surface-density
# image has 5th and 95th percentiles of 16.2 and 75.5 arcsec.
#
# The old cuts were made on R_BE, the truncation radius of the sphere, which is
# not an observable.  Nodes with R_BE between 136 and 428 arcsec have FWHMSDbs
# of only 25 to 50 arcsec, so R_BE_MAX_AS = 70 discarded every node above 1.8
# solar masses while admitting nothing that was actually large on the sky.
FWHM_MIN_AS        = getattr(_cfg, 'FWHM_MIN_AS', 15.0)
FWHM_MAX_AS        = getattr(_cfg, 'FWHM_MAX_AS', 80.0)
# JOINT_NEIGHBOURS is the number of real sources of most similar reported mass
# from which the background column and contrast of an injected core are drawn.
# Small values reproduce the mass dependence of the column most faithfully but
# reduce the variety of columns offered at a given mass.
# W_MASS, W_CONTRAST and W_SIZE weight the three terms of the node score; see
# _models_from_population.  The contrast and the size are measured directly by
# getsf on the images and are well determined, so they carry unit weight.  The
# reported mass is a spectral energy distribution fit whose systematic bias is
# what the correction method exists to remove, so matching it tightly would be
# fitting to a quantity known to be wrong; W_MASS is small by default.
# TARGET_SIZE_RANGE restricts the real sources from which the background
# column, contrast and size are drawn to those whose observed size lies in the
# given interval, in arcsec.  It exists so that a run confined to one size
# class of models is matched against the real sources of that same size class,
# rather than against the whole population.  Set to None to use every real
# source.  Give it the same interval as FWHM_MIN_AS and FWHM_MAX_AS.
TARGET_SIZE_RANGE  = getattr(_cfg, 'TARGET_SIZE_RANGE', None)
W_MASS             = float(getattr(_cfg, 'W_MASS', 0.1))
W_CONTRAST         = float(getattr(_cfg, 'W_CONTRAST', 1.0))
# W_SIZE is the weight of the observed-size term in the node score; see
# _models_from_population.  The mass and contrast terms carry unit weight, so
# W_SIZE = 1 asks for the size to be matched as tightly as the other two.
# Size is not independent of mass and contrast on a Bonnor-Ebert grid, so
# raising it degrades the other matches; measure that cost before changing it.
# Set to 0 to disable the size term.
W_SIZE             = float(getattr(_cfg, 'W_SIZE', 1.0))
JOINT_NEIGHBOURS   = int(getattr(_cfg, 'JOINT_NEIGHBOURS', 40))
# FOOTPRINT_MARGIN_AS is the radius by which the center of an injected core
# must clear the footprint of a real source.  One 500 micron beam radius,
# 18.2 arcsec, prevents an injected core from being centered on a real one
# while costing little area: with this margin the fraction of the sub-field
# available to the rungs from 3.0e21 to 4.8e22 cm^-2 falls only from 19.4, 44.4,
# 25.6, 5.7 and 0.8 per cent to 19.3, 41.8, 21.1, 3.4 and 0.3 per cent.
FOOTPRINT_MARGIN_AS = float(getattr(_cfg, 'FOOTPRINT_MARGIN_AS', 18.2))
# FOOTPRINT_MARGIN_MODE decides how far the centre of an injected core must be
# from the footprint of a REAL source.
#
#   'fixed'   FOOTPRINT_MARGIN_AS, the same for every model.  This keeps an
#             injected core from being centred on a real one but does nothing
#             about the overlap of their footprints: measured on the first
#             population-matched injection, 14% of injected cores overlapped a
#             real footprint and 9% did so by more than a tenth of the sum of
#             the two radii.  A real source inside an injected footprint
#             contributes flux that the extraction cannot attribute correctly,
#             which is the same contamination as two overlapping models.
#
#   'scaled'  (1 - MAX_FOOTPRINT_OVERLAP) * R_foot of the model being placed,
#             with R_foot = 0.5 * FOOTPRINT_FACTOR * FWHMSDbs.  Because the
#             footprint map already covers each real source out to its own
#             footprint radius, eroding by this amount leaves the injected
#             centre at least that distance beyond the real footprint edge, so
#             the two footprints overlap by no more than the permitted
#             fraction.  This is the same criterion applied between injected
#             cores, extended to the real ones.
FOOTPRINT_MARGIN_MODE = getattr(_cfg, 'FOOTPRINT_MARGIN_MODE', 'scaled')

# STAMP_SUFFIX selects which background-subtracted model stamp is injected, and
# with it which set of grid-catalogue columns describes the injected core.  The
# grid provides both, and the catalogue header defines them:
#
#   'bsl'  true crater background.  The background actually removed is the
#          floor of the depression the model digs in the cloud it displaces, so
#          the stamp is the model's own excess and is non-negative everywhere.
#   'bs'   interpolated background.  A flat background at the cloud level is
#          removed instead.  Where a model's outer envelope is rarer than the
#          cloud it replaces, the model dips BELOW that level, and the stamp is
#          negative in an annulus inside R_BE.
#
# Versions up to this one injected 'bs', on the reasoning that getsf later
# subtracts an interpolated background by the same construction, so the choice
# would cancel.  It does not.  Injecting 'bs' writes the negative annulus into
# the map, which removes flux around the core and from any neighbour reaching
# into it, and makes the source-only image negative there.  The cancellation
# argument also fails because getsf interpolates over the real map, whose
# background is not the model's embedding cloud.  15% of the grid's nodes are
# affected, rising to 56% at the highest embedding column; flag_hole_models.py
# lists them.  The default is therefore 'bsl'.
#
# The choice propagates to the selection: the contrast a node will show and its
# reported SED mass must be read from the matching set of columns, ICSD<suffix>
# and M_SED4<suffix>, or the model chosen will not be the model injected.
# CONTROL_ISOLATED produces the isolated control of a blending pair.  The
# placement is carried out in full and unchanged, consuming the random number
# generator identically, and only then are the cores that overlap a kept one
# removed, leaving a maximal non-overlapping subset in placement order.
#
# Every core that survives is therefore the same model, at the same position,
# on the same background, in the same field, as in the companion run made with
# the same seed and CONTROL_ISOLATED off.  The comparison can then be made core
# by core.  This matters: the flattened and unflattened pair, compared sample
# against sample, appeared to show a 39% bias from the cloud fluctuations that
# vanished once the same cores were compared, the apparent effect having been
# sampling.  A control produced by re-running with a stricter separation rule
# would place different models in different places and would suffer the same
# confusion; this one cannot.
#
# The truth table of the control is a strict subset of the companion's, so the
# pairing can be verified by comparing model tags and positions.
CONTROL_ISOLATED = bool(getattr(_cfg, 'CONTROL_ISOLATED', False))

STAMP_SUFFIX = getattr(_cfg, 'STAMP_SUFFIX', 'bsl')
if STAMP_SUFFIX not in ('bs', 'bsl'):
    raise SystemExit("STAMP_SUFFIX must be 'bs' or 'bsl', not %r" % STAMP_SUFFIX)


def real_source_margin_as(fwhm, r_be=0.0, tag=None):
    """Clearance required between an injected centre and a real footprint."""
    if FOOTPRINT_MARGIN_MODE == 'fixed' or MAX_FOOTPRINT_OVERLAP is None:
        return FOOTPRINT_MARGIN_AS
    return max(FOOTPRINT_MARGIN_AS,
               (1.0 - MAX_FOOTPRINT_OVERLAP) * model_radius_as(fwhm, r_be, tag))
# SIGMA_WINDOW selects the embedding window; see inject.valid_placement_mask.
# 'one-sided' reproduces version 2 and should be used only for that purpose.
SIGMA_WINDOW       = getattr(_cfg, 'SIGMA_WINDOW', 'symmetric')
R_BE_MIN_AS        = getattr(_cfg, 'R_BE_MIN_AS', None)
# SIGMA_TARGET_MIN restricts the drawn background columns to those at or above
# it.  Below about 5e21 cm^-2 the grid cannot reach the contrast that real cores
# have there: a core of 0.15 Msun and 15-50 arcsec would need a central column of
# only ~7e20 cm^-2 to show a contrast of 1.18 on a 4e21 background, and no
# Bonnor-Ebert node is that faint.  The sampler then accepts a large contrast
# error, giving injected cores of contrast ~2 wherever the column is low.  The
# same limit, 5e21, was used for model placement in the original Aquila
# completeness simulations.
SIGMA_TARGET_MIN   = getattr(_cfg, 'SIGMA_TARGET_MIN', None)
# JOINT_TARGET_FILE holds three columns per real source: reported mass,
# background column, and contrast.  When given, it supersedes
# SIGMA_TARGET_FILE and CONTRAST_TARGET_FILE: for each drawn mass the
# background and contrast are taken from a real source of SIMILAR mass, so the
# coupling between the three is preserved.  In Aquila that coupling is strong,
# with Spearman r(log M, log Sigma) = +0.73, and drawing them independently
# places cores of a given mass in regions far less dense than they occupy in
# reality, which makes them stand out too clearly and be measured too easily.
JOINT_TARGET_FILE  = getattr(_cfg, 'JOINT_TARGET_FILE', None)
# MODEL_PICK_TOLERANCE spreads the choice of grid node over the nodes that fit
# nearly as well as the closest one, instead of always taking the best match.
# Each node is scored by a squared distance in base-10 logarithms,
#     d = (log M - log M_node)^2 + (log Sigma - log Sigma_node)^2
#         + (log C - log C_node)^2,
# and is then chosen with probability proportional to exp(-d / TOL).  TOL
# therefore has the units of d, squared dex; it is a selection tolerance and has
# nothing to do with any physical temperature.  sqrt(TOL) is the mismatch, in
# dex, that halves a node's weight roughly: TOL = 0.005 corresponds to 0.07 dex,
# about 17% spread over the three quantities, while TOL = 0.15 corresponds to
# 0.39 dex, a factor of 2.4, which destroys the match.  TOL = 0 always takes the
# single best node.
#
# Some spreading is needed because with mass, background column and contrast all
# constrained at once the best-match rule collapses onto a few nodes: the s2028
# run drew 253 cores from only 34 distinct models, five of which supplied 63% of
# them.  On this grid the second-nearest node is materially worse, however, so
# the fidelity falls as TOL rises; 0.005 buys a third more diversity at
# negligible cost, and larger values are not worth it.
MODEL_PICK_TOLERANCE = float(getattr(_cfg, 'MODEL_PICK_TOLERANCE', 0.005))
# R_BE_MAX_AS was previously read only in the multi-model branch, so a
# single-model config silently ignored it.  Bound here for both formats.
R_BE_MAX_AS        = globals().get('R_BE_MAX_AS',
                                   getattr(_cfg, 'R_BE_MAX_AS', None))
STAMP_J_PREFIX     = getattr(_cfg, 'STAMP_J_PREFIX', STAMP_J_PREFIX)
# Separation between two placed cores is SEP_FACTOR * (r_i + r_j), with
# r = sqrt(R_BE^2 + BEAM500^2) the convolved radius.  SEP_FACTOR = 1.5 is the
# value calibrated empirically against the 500 micron footprints; lower it only
# after measuring the realised gaps with check_separation.py, since the gap
# scales with (r_i + r_j) and a global change affects large pairs most.
SEP_FACTOR         = float(getattr(_cfg, 'SEP_FACTOR', 1.5))
# AVOID_REAL_FOOTPRINTS controls whether the footprints of the real sources are
# forbidden to the centers of injected cores.  In version 2 this was switched
# off because the exclusion appeared to cost 87% of the sub-field.  That figure
# was an artifact: the footprints themselves cover 6.5% of the field, in 179
# filled regions of median area 242 pixels, and the 87% arose from eroding the
# permitted region by the whole R_BE disk, which for R_BE = 70 arcsec dilates
# each footprint by 23 pixels.  Version 3 applies the exclusion to the core
# center with the fixed margin FOOTPRINT_MARGIN_AS, so the true cost is a few
# per cent, and the default is therefore on.  What has to be prevented is
# centering an injected core on a real one, which makes the extraction a blend
# of the two; overlap of the outer envelope with a real footprint is harmless
# and in any case unavoidable in a real cloud.
AVOID_REAL_FOOTPRINTS = bool(getattr(_cfg, 'AVOID_REAL_FOOTPRINTS', True))
# OVERLAP_FREE_R_BE_AS separates compact models from large ones for the purpose
# of the non-overlap criterion.  Requiring every pair to be separated is too
# strong: a large, faint, flat-topped model is barely detectable against the
# cloud and does not disturb the measurement of a small core lying on top of it,
# yet its exclusion zone denies that core the dense filament where it belongs.
# The criterion is therefore applied only within a class: two compact models may
# not overlap, and two large models may not overlap either, since intersecting
# flat tops would double the intensity over an extended area and create an
# artifact.  A compact model may be placed on a large one.  Set to None to
# restore the criterion for every pair.
#
# In version 3 the class boundary and the exclusion radius are both expressed
# in the observed size FWHMSDbs rather than in R_BE, for the reason given in
# point 2 of the module docstring.  The default, 50 arcsec, is a little above
# the median AFWHM of the real Aquila sources, 37.8 arcsec.
OVERLAP_FREE_FWHM_AS = getattr(_cfg, 'OVERLAP_FREE_FWHM_AS', 50.0)
# MAX_FOOTPRINT_OVERLAP, when set, replaces the size-class rule above by a
# criterion applied to EVERY pair: the footprints of two injected cores may
# interpenetrate by at most this fraction of the sum of their footprint radii,
# so that
#     centre separation  >=  (1 - MAX_FOOTPRINT_OVERLAP) * (R_foot_i + R_foot_j)
# with R_foot = 0.5 * FOOTPRINT_FACTOR * FWHMSDbs.
#
# The size-class exemption it replaces let a compact model be placed on an
# extended one without any separation requirement, on the argument that a large
# faint model is barely detectable against the cloud and would not disturb a
# small core lying on it.  Measured on the first population-matched injection,
# that argument fails: 36% of injected cores ended up with a companion closer
# than the sum of their two half-maximum radii, every close pair was a
# cross-class pair, the closest was at 0.11 of that sum, and the error in the
# recovered mass correlates with crowding at +0.42 (probability 0.011) in the
# flattened run, crowded cores losing flux to their companions.
MAX_FOOTPRINT_OVERLAP = getattr(_cfg, 'MAX_FOOTPRINT_OVERLAP', 0.10)
# Ratio of the full footprint major axis to the half-maximum width, FOOA/AFWHM.
# Measured at 1.8 to 2.0 across seven clouds and set by the extraction rather
# than by the sources.
FOOTPRINT_FACTOR = float(getattr(_cfg, 'FOOTPRINT_FACTOR', 1.84))


# Radius enclosing FLUX_FRACTION of each model's flux, read once from the
# profiles catalogue and cached by node tag.  BES_PROFILES may be set in the
# config; by default it sits beside BES_CATALOG under the standard name.
FLUX_FRACTION = float(getattr(_cfg, 'FLUX_FRACTION', 0.95))
# `or` rather than a getattr default: a config that sets BES_PROFILES = None to
# mean "use the default" would otherwise pass None straight through, because
# the attribute exists.
BES_PROFILES = getattr(_cfg, 'BES_PROFILES', None) or os.path.join(
    os.path.dirname(os.path.abspath(_bes_catalog_path)),
    'bes_model_grid_final2_profiles')
_R_FLUX = None


def _flux_radii(path=None, frac=None):
    """{node tag: radius enclosing `frac` of the model's flux}, in arcsec.

    Computed from the azimuthally averaged surface-density profiles, weighting
    each radial bin by 2 pi r I(r) dr on the uniform radial grid the profiles
    use.  Returns an empty dict, with a warning, if the file is absent, so that
    the caller can fall back on the geometric radii.
    """
    global _R_FLUX
    if _R_FLUX is not None:
        return _R_FLUX
    path = path or BES_PROFILES
    frac = FLUX_FRACTION if frac is None else frac
    prof = {}
    try:
        if not path or not os.path.exists(path):
            raise IOError('no such file: %r' % (path,))
        for line in open(path):
            if not line.strip() or line.lstrip()[0] == '#':
                continue
            f = line.split()
            if f[3] != 'SD':
                continue
            tag = 'i%02dj%02dk%02d' % (int(f[0]), int(f[1]), int(f[2]))
            prof.setdefault(tag, []).append((float(f[5]), float(f[6])))
    except (IOError, OSError, TypeError, ValueError, IndexError) as _e:
        print('  NOTE: the profiles catalogue could not be read (%s); '
              'exclusion radii fall back to the larger of R_BE and the '
              'observed footprint, which is conservative for concentrated '
              'models and may drop some of them from the injection' % _e)
        _R_FLUX = {}
        return _R_FLUX
    out = {}
    for tag, pts in prof.items():
        a = np.asarray(sorted(pts), float)
        r, I = a[:, 0], a[:, 1]
        w = np.cumsum(np.maximum(I, 0.0) * r)
        if w[-1] <= 0:
            continue
        out[tag] = float(np.interp(frac, w / w[-1], r))
    print('  exclusion radii: %d nodes have a %.0f%%-of-flux radius from %s'
          % (len(out), 100 * frac, os.path.basename(path)))
    _R_FLUX = out
    return _R_FLUX


def model_radius_as(fwhm, r_be, tag=None):
    """Radius, in arcsec, out to which a model must be kept clear of others.

    Two radii describe an injected model and they are not the same thing.

      TRUE footprint      R_BE, the truncation radius of the sphere.  All of
                          the model's signal lies inside it and none outside,
                          since the injected stamp has the crater background
                          removed.  This is the footprint in the physical
                          sense.
      OBSERVED footprint  0.5 * FOOTPRINT_FACTOR * FWHMSDbs, the radius getsf
                          would assign, set by the extraction rather than by
                          the source.  This is the area over which the flux is
                          actually measured.

    Either can be the larger.  Over the models the sampler places, the median
    ratio of R_BE to the observed footprint radius is 0.68, so the observed one
    usually dominates; but for the concentrated, large-xi_max models it does
    not, and one of them reaches R_BE = 199 arcsec on an observed width of only
    33 arcsec, a ratio of six.  Separating such a model on its observed
    footprint alone leaves its envelope free to swallow a compact neighbour.

    Neither, however, is the right radius for deciding whether two cores
    contaminate each other.  R_BE is where the signal formally stops, but for a
    concentrated model the outer envelope is far too faint to affect anything:
    node i03j18k08 has R_BE = 631 arcsec while 95% of its flux lies within 43.
    Enforcing R_BE clearance would exclude such models from a field containing
    real sources altogether, for the sake of a few per cent of their flux
    spread over a disk fifteen times wider.

    The radius used is therefore the one enclosing FLUX_FRACTION of the model's
    flux, measured from its own profile, and never less than the observed
    footprint, so that neither the bulk of the signal nor the area over which
    the flux is measured reaches into another core.  Without the profiles
    catalogue it falls back to the larger of R_BE and the observed footprint.
    """
    r_obs = 0.5 * FOOTPRINT_FACTOR * float(fwhm)
    if tag is not None:
        r_flux = _flux_radii().get(tag)
        if r_flux is not None and np.isfinite(r_flux) and r_flux > 0:
            return max(float(r_flux), r_obs)
    return max(float(r_be), r_obs)


def min_separation_as(rad_a, rad_b):
    """Smallest permitted centre separation of two injected cores, in arcsec.

    Arguments are the radii from model_radius_as.  With MAX_FOOTPRINT_OVERLAP
    set, the two may overlap by at most that fraction of the sum of their
    radii, and the rule applies to every pair.  Otherwise the older rule is
    used, in which the separation is SEP_FACTOR times the sum of the two radii.
    """
    if MAX_FOOTPRINT_OVERLAP is not None:
        return (1.0 - MAX_FOOTPRINT_OVERLAP) * (rad_a + rad_b)
    return SEP_FACTOR * (rad_a + rad_b)


def separation_applies(fwhm_a, fwhm_b):  # noqa: C901
    """Whether the criterion binds for this pair.

    With MAX_FOOTPRINT_OVERLAP set it binds for every pair.  Otherwise it binds
    only within a size class, which is the behaviour of run_inject_v2.py.
    """
    if MAX_FOOTPRINT_OVERLAP is not None:
        return True
    if OVERLAP_FREE_FWHM_AS is None:
        return True
    return (fwhm_a <= OVERLAP_FREE_FWHM_AS) == (fwhm_b <= OVERLAP_FREE_FWHM_AS)
OVERLAP_FREE_R_BE_AS = getattr(_cfg, 'OVERLAP_FREE_R_BE_AS', 50.0)
# FLATTEN_MAX_R_BE_AS restricts background flattening to models no larger than
# this, defaulting to the same threshold that governs overlap.  Interpolating
# the background under a large footprint is wrong on three counts: it removes a
# large area of genuine cloud structure, and so removes the very fluctuations
# that smaller cores overlapping that model are supposed to experience; the
# interpolation itself becomes progressively less accurate as the footprint
# grows, with an error of either sign; and it is very slow.  The same loss of
# accuracy affects getsf's own background subtraction for large footprints, and
# is a bias to keep in mind when interpreting recovered masses.
# Expressed in observed size in version 3, for consistency with the other size
# thresholds.
FLATTEN_MAX_FWHM_AS = getattr(_cfg, 'FLATTEN_MAX_FWHM_AS', OVERLAP_FREE_FWHM_AS)
FLATTEN_MAX_R_BE_AS = getattr(_cfg, 'FLATTEN_MAX_R_BE_AS', OVERLAP_FREE_R_BE_AS)
FLATTEN_BACKGROUND = getattr(_cfg, 'FLATTEN_BACKGROUND', False)
# Retired in version 3.  A configuration that still sets them is telling
# run_inject to do something it no longer does, so say so plainly.
for _dead, _live in (('R_BE_MIN_AS', 'FWHM_MIN_AS'),
                     ('R_BE_MAX_AS', 'FWHM_MAX_AS'),
                     ('OVERLAP_FREE_R_BE_AS', 'OVERLAP_FREE_FWHM_AS'),
                     ('SIGMA_TARGET_FILE', 'JOINT_TARGET_FILE'),
                     ('CONTRAST_TARGET_FILE', 'JOINT_TARGET_FILE'),
                     ('SIGMA_TARGET_MIN', 'JOINT_TARGET_FILE')):
    if getattr(_cfg, _dead, None) is not None:
        print('  NOTE: %s is set in the configuration but is ignored by '
              'run_inject_v3.py; use %s instead' % (_dead, _live))
# Restrict the band list to the bands the configuration actually provides.
# inject.BANDS is ['000', '070', '160', '250', '350', '500'], where '000' is the
# high-resolution surface-density map, supplied through HIRES_SURFDENS_PATH.  A
# configuration that omits a band previously failed with a bare KeyError deep in
# the file inventory; now the band is dropped with a printed note.  Set
# HIRES_SURFDENS_PATH in the config if the surface-density band is wanted.
_bands_have = [b for b in inject.BANDS
               if IMG_PATHS.get(b) and OMASK_PATHS.get(b)]
_bands_miss = [b for b in inject.BANDS if b not in _bands_have]
if _bands_miss:
    _vprint('  bands omitted (no image or observation mask in the config): %s'
          % ', '.join(_bands_miss))
    if '000' in _bands_miss:
        _vprint('    note: band 000 is the surface-density map that the correction')
        _vprint('    itself works in -- Sigma_cloud, the concentration zeta, the')
        _vprint('    footprint factor phi and the footprint radius are all measured')
        _vprint('    there.  Without it the injected cores are absent from that map')
        _vprint('    and the extraction will not exercise the correction.')
        _vprint('    SIGMA_PATH is used read-only, for placement validity and for')
        _vprint('    the local_Sigma of each core from the PRE-injection map.')
        _vprint('    To also inject into it and write an injected copy, add')
        _vprint('    to the config:')
        _vprint('        HIRES_SURFDENS_PATH = SIGMA_PATH')
        _vprint('    Loading the same file twice is intended: one copy stays')
        _vprint('    pristine as the placement and truth reference, the other')
        _vprint('    receives the cores.')
if not _bands_have:
    raise SystemExit('no usable bands: check IMG_PATHS and OMASK_PATHS')
inject.BANDS = _bands_have

if CMF_SLOPE is not None and CMF_N_CORES:
    # In core-mass-function mode the models are drawn, so a single MODEL_TAG
    # from the config would be misleading in every output filename.  The tag is
    # rebuilt from what actually defines the run, including the seed so that
    # realisations do not overwrite one another.  A SET_TAG given in the config
    # is therefore discarded; say so, rather than leaving the user to wonder
    # why the output files carry a name they did not choose.
    _cfg_tag = getattr(_cfg, 'SET_TAG', None)
    SET_TAG = 'cmf%.2f_n%d_s%d' % (CMF_SLOPE, CMF_N_CORES, RANDOM_SEED)
    if FLATTEN_BACKGROUND:
        SET_TAG = SET_TAG + '_flat'
    if CONTROL_ISOLATED:
        SET_TAG = SET_TAG + '_iso'
    if SCALE_FACTOR != 1.0:
        SET_TAG = SET_TAG + '_x%.4g' % SCALE_FACTOR
    if _cfg_tag and _cfg_tag != SET_TAG:
        print('  NOTE: SET_TAG = "%s" in the config is not used in core mass '
              'function mode.' % _cfg_tag)
        print('        Output files are named from the sampling instead: "%s".'
              % SET_TAG)
        print('        The suffix _flat is appended automatically when '
              'FLATTEN_BACKGROUND is on,')
        print('        so a flattened companion run never overwrites its '
              'unflattened counterpart.')
    _vprint('  core mass function mode, dN/dM ~ M^-%.2f, %d cores, '
            'flatten=%s' % (CMF_SLOPE, CMF_N_CORES, FLATTEN_BACKGROUND))
    _vprint('  output set tag "%s"' % SET_TAG)



# Everything the v2 setup prints is mirrored here and written into the header of
# the truth table, so that a realisation documents the sampling that produced it.
_V2_LOG = []


def _vprint(msg):
    print(msg)
    _V2_LOG.append(msg)


# ===========================================================================
# v2: core-mass-function sampling and contrast-matched model selection
# ===========================================================================

def _draw_cmf_masses(n, alpha, m_lo, m_hi, rng):
    """Draw n masses from dN/dM proportional to M^(-alpha) on [m_lo, m_hi].

    Inverse transform of the truncated power law.  alpha = 1 is handled
    separately because the integral becomes logarithmic there.
    """
    u = rng.random(n)
    if abs(alpha - 1.0) < 1e-8:
        return m_lo * (m_hi / m_lo) ** u
    p = 1.0 - alpha
    return (m_lo ** p + u * (m_hi ** p - m_lo ** p)) ** (1.0 / p)


def _grid_column(name, n_expected):
    """Read one column of the Bonnor-Ebert grid catalogue by its header name.

    _GRID as returned by fit_mass.load_catalog carries only the basic model
    parameters, so quantities such as ICSDbs, the beam-convolved surface density
    at the model centre, are read from the catalogue file itself.  The column is
    located by the position of its name on the commented header line, so this
    does not depend on the column count.
    """
    try:
        lines = open(_bes_catalog_path).read().splitlines()
    except Exception:
        return np.full(n_expected, np.nan)
    hdr = None
    for ln in lines:
        if ln.lstrip()[:1] == '#' and name in ln.split():
            hdr = ln.lstrip('# ').split()
    if hdr is None or name not in hdr:
        print('  note: column %s not found in the grid catalogue; '
              'contrast matching disabled' % name)
        return np.full(n_expected, np.nan)
    j = hdr.index(name)
    out = []
    for ln in lines:
        if not ln.strip() or ln.lstrip()[:1] == '#':
            continue
        f = ln.split()
        out.append(float(f[j]) if j < len(f) else np.nan)
    out = np.array(out, dtype=float)
    return out if len(out) == n_expected else np.full(n_expected, np.nan)


def _grid_arrays():
    """Per-node arrays of the Bonnor-Ebert grid, returned as a dict.

    Keys, all of the same length, one entry per grid node:

      tag       node label, 'iNNjNNkNN'
      M_BE      true Bonnor-Ebert mass                              (M_sun)
      M_SED     reported mass from a four-band SED fit, M_SED4bs    (M_sun)
      SD_emb    column density of the cloud the model is embedded in (cm^-2)
      R_BE_as   truncation radius of the sphere                     (arcsec)
      FWHM_as   major axis at half maximum of the model in the
                surface-density image, FWHMSDbs                     (arcsec)
      ICSDbs    background-subtracted central column of the model,
                convolved to the surface-density beam               (cm^-2)

    FWHM_as is the observed size and is the quantity comparable with the
    AFWHM of a real source; R_BE_as is a model parameter and is typically
    several times larger.  M_SED is the quantity comparable with the reported
    mass of a real source; M_BE is the truth the correction has to recover.
    """
    i = np.asarray(_GRID['i'], dtype=int)
    j = np.asarray(_GRID['j'], dtype=int)
    k = np.asarray(_GRID['k'], dtype=int)
    tags = np.array(['i%02dj%02dk%02d' % (p, q, r) for p, q, r in zip(i, j, k)])
    if len(tags) == 0:
        raise ValueError('the Bonnor-Ebert grid catalogue produced no nodes; '
                         'check BES_CATALOG in the config file')
    n = len(tags)
    return dict(tag=tags,
                M_BE=np.asarray(_GRID['M_BE'], dtype=float),
                M_SED=_grid_column('M_SED4' + STAMP_SUFFIX, n),
                SD_emb=np.asarray(_GRID['SD_emb'], dtype=float),
                R_BE_as=np.asarray(_GRID['R_BE_as'], dtype=float),
                FWHM_as=_grid_column('FWHMSD' + STAMP_SUFFIX, n),
                ICSDbs=_grid_column('ICSD' + STAMP_SUFFIX, n))


def _models_from_population(n_cores, alpha, m_lo, m_hi, rng, joint_target,
                            fwhm_min=None, fwhm_max=None):
    """Choose, for each core to be injected, a grid node and a target column.

    The procedure has three steps.

    1.  A reported mass M is drawn from the core mass function,
        dN/dM proportional to M^-alpha, on [m_lo, m_hi].

    2.  A real source of similar reported mass is drawn from the target table,
        and its background column Sigma and contrast C are adopted as the
        target for this core.  Drawing the pair from one real source preserves
        the coupling between mass, column and contrast, which in Aquila is
        strong: the correlation of log10(M_reported) with log10(Sigma_cloud)
        is +0.74 and that of log10(Sigma_cloud) with log10(contrast - 1) is
        +0.49.  Drawing them independently would impose the population-median
        contrast at every column, which is wrong at both ends.

    3.  The grid node is chosen among those that may legally be placed at that
        column, that is those whose embedding column SD_emb lies within a
        factor sqrt(2) of Sigma.  Because the rungs of SD_emb are spaced by a
        factor of 2, that window is exactly one rung wide and every column has
        exactly one eligible rung; there is no gap, and no fallback is needed.
        Within the rung the node is scored by

            d = W_MASS     * (log10 M       - log10 M_SED)^2
              + W_CONTRAST * (log10 (C - 1)  - log10 (C_node - 1))^2
              + W_SIZE     * (log10 A        - log10 FWHMSDbs)^2,

        where M_SED is the node's own reported four-band SED mass, the
        like-for-like counterpart of the drawn reported mass,

            C_node = 1 + ICSDbs / Sigma

        is the contrast the node would show at the column it will actually sit
        at, and A is the major axis at half maximum of the real source in the
        surface-density image, the counterpart of the node's FWHMSDbs.  The
        getsf definition of contrast is PEAK^SBF / PEAK^BGF, that is
        (source + background) / background, so it exceeds unity; ICSDbs is the
        model's background-subtracted central column, the counterpart of
        PEAK^SRC.

    The contrast enters as C - 1, not as C.  The contrast itself lies between
    about 1.1 and 1.8 over the real Aquila sources, a logarithmic spread of
    only 0.09, so a selection error of 0.04 in log10 C, which is what scoring
    on C directly produced, is half the entire spread of the population and
    destroys the rank correlation of contrast with column: the injected cores
    had +0.242 against +0.512 for the real sources.  The quantity
    C - 1 = ICSDbs / Sigma is the ratio of the source to its background, it
    spans 0.87 in log10 over the same sources, and scoring on it weights the
    contrast comparably with the mass and the size.

    The three terms are not of equal standing.  The contrast and the size are
    quantities getsf measures directly on the images and are well determined.
    The reported mass is not: it comes from a spectral energy distribution fit
    whose systematic bias is the very thing this work sets out to correct, so
    requiring the injected cores to reproduce it closely would be fitting to a
    quantity known to be wrong.  W_MASS is therefore small by default.  The
    mass of an injected core is not left undetermined by this: it follows from
    the node the observables select, and the truth table records the true mass
    M_BE, which is what any later comparison uses.

    The size term is new relative to the first version 3 draft.  Without it
    the injected cores came out systematically larger than the real ones,
    43.1 against 37.8 arcsec at the median, with a Kolmogorov-Smirnov
    statistic of 0.479 between the two distributions of size, by far the worst
    matched of the four quantities compared.  Size is not free to choose once
    the mass and the contrast are fixed, so W_SIZE trades one match against
    the others and should not be raised without measuring what it costs.

    Two differences from version 2 matter.  The mass is scored against M_SED,
    not against the true mass M_BE: over the eligible nodes the ratio
    M_BE / M_SED4bs has median 1.105, so scoring against M_BE selected nodes
    that were systematically too light by 0.043 in base-10 logarithm.  And the
    eligible set is defined by the symmetric window, so the nearest-rung
    fallback of version 2, which fired for half of all drawn columns and always
    resolved upward, is gone.

    Nodes are restricted by their observed size FWHMSDbs, not by R_BE.  See the
    module docstring, point 2.

    Returns a list of dicts, one per distinct grid node used, carrying the
    number of cores to place, the individual target columns drawn for them, and
    the node's observed size.
    """
    g = _grid_arrays()
    tags = g['tag']
    ok = (np.isfinite(g['M_SED']) & (g['M_SED'] > 0)
          & np.isfinite(g['SD_emb']) & (g['SD_emb'] > 0)
          & np.isfinite(g['ICSDbs'])
          & np.isfinite(g['FWHM_as']) & (g['FWHM_as'] > 0))
    n_before = int(ok.sum())
    if fwhm_min is not None:
        ok = ok & (g['FWHM_as'] >= fwhm_min)
    if fwhm_max is not None:
        ok = ok & (g['FWHM_as'] <= fwhm_max)
    _vprint('  observed-size cut FWHMSDbs in [%s, %s] arcsec: '
            '%d of %d grid nodes retained'
            % ('%.1f' % fwhm_min if fwhm_min is not None else '-',
               '%.1f' % fwhm_max if fwhm_max is not None else '-',
               int(ok.sum()), n_before))
    if not ok.any():
        raise ValueError('the observed-size cut excludes every grid node')

    tags = tags[ok]
    msed = g['M_SED'][ok]
    mbe = g['M_BE'][ok]
    sde = g['SD_emb'][ok]
    icsd = g['ICSDbs'][ok]
    fwhm = g['FWHM_as'][ok]
    rbe = g['R_BE_as'][ok]
    lmsed = np.log10(msed)

    if joint_target is None:
        raise ValueError('run_inject_v3.py requires JOINT_TARGET_FILE')
    jM, jS, jC, jA = joint_target
    if TARGET_SIZE_RANGE is not None:
        _lo, _hi = TARGET_SIZE_RANGE
        _k = np.isfinite(jA) & (jA >= _lo) & (jA <= _hi)
        _vprint('  target sources restricted to observed size %.1f to %.1f '
                'arcsec: %d of %d real sources kept'
                % (_lo, _hi, int(_k.sum()), len(jA)))
        if _k.sum() < 20:
            raise ValueError('TARGET_SIZE_RANGE leaves only %d real sources'
                             % int(_k.sum()))
        jM, jS, jC, jA = jM[_k], jS[_k], jC[_k], jA[_k]
    ljM = np.log10(jM)
    lfw = np.log10(fwhm)
    use_size = bool(W_SIZE > 0 and np.isfinite(jA).any())
    if W_SIZE > 0 and not use_size:
        _vprint('  note: the target table carries no size column, so the '
                'size term of the node score is disabled')

    masses = _draw_cmf_masses(n_cores, alpha, m_lo, m_hi, rng)

    s2 = np.sqrt(2.0)
    counts = {}
    tgt_of = {}
    chosen_msed, chosen_mbe, chosen_c, chosen_fw = [], [], [], []
    drawn_mass, drawn_sig, drawn_con, drawn_siz = [], [], [], []
    n_unreachable = 0
    for M in masses:
        # a real source of similar reported mass supplies the column, the
        # contrast and the size; JOINT_NEIGHBOURS controls how tightly
        # "similar" is meant
        near = np.argsort(np.abs(ljM - np.log10(M)))[:JOINT_NEIGHBOURS]
        pick = int(near[rng.integers(0, len(near))])
        Sg, Cn, An = float(jS[pick]), float(jC[pick]), float(jA[pick])

        cand = np.where((sde / s2 <= Sg) & (Sg < sde * s2))[0]
        if len(cand) == 0:
            # only possible below the lowest rung or above the highest; such a
            # column cannot be imitated by any model and the draw is discarded
            n_unreachable += 1
            continue
        cgrid = 1.0 + icsd[cand] / Sg
        # scored on C - 1, the source-to-background ratio; see the docstring
        d = (W_MASS * (np.log10(M) - lmsed[cand]) ** 2
             + W_CONTRAST * (np.log10(np.maximum(cgrid - 1.0, 1e-6))
                             - np.log10(max(Cn - 1.0, 1e-6))) ** 2)
        if use_size and np.isfinite(An) and An > 0:
            d = d + W_SIZE * (np.log10(An) - lfw[cand]) ** 2
        if MODEL_PICK_TOLERANCE > 0:
            w = np.exp(-(d - d.min()) / MODEL_PICK_TOLERANCE)
            ssum = w.sum()
            b = int(cand[rng.choice(len(d), p=w / ssum)]) \
                if (np.isfinite(ssum) and ssum > 0) else int(cand[np.argmin(d)])
        else:
            b = int(cand[np.argmin(d)])
        counts[tags[b]] = counts.get(tags[b], 0) + 1
        # every core keeps its own target column, contrast and size, so that
        # placement can steer each one individually.  Version 2, and the first
        # version 3 draft, kept only the median column per node, which
        # collapsed the spread of columns within a node and halved the
        # correlation between contrast and column in the injected sample.
        tgt_of.setdefault(tags[b], []).append((Sg, Cn, An))
        chosen_msed.append(msed[b]); chosen_mbe.append(mbe[b])
        chosen_c.append(1.0 + icsd[b] / Sg); chosen_fw.append(fwhm[b])
        drawn_mass.append(M); drawn_sig.append(Sg)
        drawn_con.append(Cn); drawn_siz.append(An)

    chosen_msed = np.asarray(chosen_msed); chosen_mbe = np.asarray(chosen_mbe)
    chosen_c = np.asarray(chosen_c); chosen_fw = np.asarray(chosen_fw)
    drawn_mass = np.asarray(drawn_mass)
    drawn_sig = np.asarray(drawn_sig); drawn_con = np.asarray(drawn_con)
    drawn_siz = np.asarray(drawn_siz)
    n_ok = len(chosen_msed)
    if n_ok == 0:
        raise ValueError('no core could be assigned a grid node')

    _vprint('Core mass function sampling:')
    _vprint('  dN/dM proportional to M^(-%.2f)  '
            '(dN/dlogM proportional to M^(-%.2f))' % (alpha, alpha - 1.0))
    _vprint('  %d reported masses drawn on [%.3g, %.3g] M_sun; median %.3g M_sun'
            % (n_cores, m_lo, m_hi, np.median(masses)))
    if n_unreachable:
        _vprint('  %d of %d draws discarded: the background column of the real '
                'source drawn lies outside every embedding rung'
                % (n_unreachable, n_cores))
    _vprint('  %d cores assigned to %d distinct grid nodes' % (n_ok, len(counts)))
    _vprint('  drawn reported mass versus node reported mass M_SED4bs: '
            'median %.3g versus %.3g M_sun, median |log10 ratio| %.3f dex'
            % (np.median(drawn_mass), np.median(chosen_msed),
               np.median(np.abs(np.log10(chosen_msed / drawn_mass)))))
    _vprint('  drawn contrast versus node contrast at the drawn column: '
            'median %.3f versus %.3f, median |log10 ratio| %.3f dex'
            % (np.median(drawn_con), np.median(chosen_c),
               np.median(np.abs(np.log10(chosen_c / drawn_con)))))
    _f = np.isfinite(drawn_siz) & (drawn_siz > 0)
    if _f.any():
        _vprint('  drawn observed size versus node size FWHMSDbs: '
                'median %.1f versus %.1f arcsec, median |log10 ratio| %.3f dex'
                % (np.median(drawn_siz[_f]), np.median(chosen_fw[_f]),
                   np.median(np.abs(np.log10(chosen_fw[_f] / drawn_siz[_f])))))
    _vprint('  target background column: median %.2e cm^-2 '
            '(5th %.2e, 95th %.2e)'
            % (np.median(drawn_sig), *np.percentile(drawn_sig, [5, 95])))
    # The mapping onto discrete grid nodes changes the mass distribution, so
    # the slope actually placed is not the nominal input.  The truth table, not
    # the nominal slope, is always the reference.
    for mmin in (0.1, 0.2):
        v = chosen_mbe[chosen_mbe >= mmin]
        if len(v) > 10:
            x = len(v) / np.sum(np.log(v / mmin))
            _vprint('  slope of the true masses M_BE actually assigned, above '
                    '%.2f M_sun: x = %.2f +/- %.2f  (nominal input x = %.2f)'
                    % (mmin, x, x / np.sqrt(len(v)), alpha - 1.0))

    fwhm_of = {t: float(fwhm[list(tags).index(t)]) for t in counts}
    rbe_of = {t: float(rbe[list(tags).index(t)]) for t in counts}
    out = []
    for t, c in sorted(counts.items()):
        trip = tgt_of.get(t, [])
        out.append(dict(tag=t, n_cores=c,
                        fwhm_as=fwhm_of[t], r_be_as=rbe_of[t],
                        # one entry per core assigned to this node: the
                        # background column, contrast and size of the real
                        # source it is imitating
                        targets=trip,
                        sigma_targets=[q[0] for q in trip],
                        contrast_targets=[q[1] for q in trip],
                        size_targets=[q[2] for q in trip],
                        sigma_target=float(np.nanmedian([q[0] for q in trip]))
                        if trip else np.nan))
    return out


def _load_joint_target(path):
    """Read the joint target table written by build_joint_target_v3.py.

    Four columns are expected, one row per real source:
        reported SED mass (M_sun), background column density (cm^-2),
        contrast PEAK^SBF/PEAK^BGF (dimensionless, greater than unity),
        and major axis at half maximum in the surface-density image (arcsec).

    A three-column table written by an earlier version is still accepted; the
    size is then returned as not-a-number and the size term drops out of the
    node score.
    """
    if not path:
        return None
    M, S, C, A = [], [], [], []
    for line in open(path):
        line = line.strip()
        if not line or line[0] in '#!':
            continue
        f = line.split()
        if len(f) < 3:
            continue
        try:
            a, b, c = float(f[0]), float(f[1]), float(f[2])
            d = float(f[3]) if len(f) > 3 else np.nan
        except ValueError:
            continue
        if a > 0 and b > 0 and c > 1:
            M.append(a); S.append(b); C.append(c); A.append(d)
    if not M:
        raise ValueError('no usable rows in %s' % path)
    return np.array(M), np.array(S), np.array(C), np.array(A)


def _load_sigma_target(path):
    """Read one background column density per line, in cm^-2."""
    if not path:
        return None
    v = []
    for line in open(path):
        line = line.strip()
        if not line or line[0] in '#!':
            continue
        try:
            x = float(line.split()[0])
        except ValueError:
            continue
        if np.isfinite(x) and x > 0:
            v.append(x)
    if not v:
        raise ValueError('no usable values in %s' % path)
    return np.array(v)


def main():

    # ------------------------------------------------------------------
    # 0. File inventory
    # ------------------------------------------------------------------
    def _info(label, path):
        abspath = os.path.abspath(path)
        if not os.path.exists(abspath):
            print(f'  {label:30s}  MISSING  {abspath}'); return
        d = fits.getdata(abspath).astype(float)
        print(f'  {label:30s}  shape={d.shape}  '
              f'min={d.min():.3g}  max={d.max():.3g}  {abspath}')

    _rng_cmf = np.random.default_rng(RANDOM_SEED)
    if CMF_SLOPE is not None and CMF_N_CORES:
        MODELS = [_normalise_model_entry(m, STAMP_ROOT)
                  for m in _models_from_population(
                      CMF_N_CORES, CMF_SLOPE,
                      CMF_MASS_RANGE[0], CMF_MASS_RANGE[1],
                      _rng_cmf,
                      _load_joint_target(JOINT_TARGET_FILE),
                      fwhm_min=FWHM_MIN_AS, fwhm_max=FWHM_MAX_AS)]

    print('File inventory:')
    for b in inject.BANDS:
        _info(f'img {b}um', IMG_PATHS[b])
    _info('sigma map',  SIGMA_PATH)
    _info('sigma omask',SIGMA_OMASK_PATH)
    _info('footprints', FOOTS_PATH)
    for m in MODELS:
        for b,p in m['stamp_files'].items():
            if p: _info(f'stamp {m["tag"]} {b}um', p)
    print()

    # ------------------------------------------------------------------
    # 1. Load field
    # ------------------------------------------------------------------
    print('Loading field maps ...')
    field = inject.load_field(
        IMG_PATHS, OMASK_PATHS,
        sigma_path=SIGMA_PATH,
        sigma_omask_path=SIGMA_OMASK_PATH,
    )
    print(f'  field shape: {field["shape"]}')
    print(f'  coverage pixels: {field["coverage"].sum()}')

    if SCALE_FACTOR != 1.0:
        print(f'  Scaling all field images and sigma map by {SCALE_FACTOR:.4g} ...')
        for b in inject.BANDS:
            field['img'][b] = field['img'][b] * SCALE_FACTOR
        field['sigma'] = field['sigma'] * SCALE_FACTOR
        print(f'  Sigma range after scaling: {field["sigma"][field["sigma"]>0].min():.2e}'
              f' -- {field["sigma"].max():.2e} cm-2')

    # ------------------------------------------------------------------
    # 2. Load stamps for each model
    # ------------------------------------------------------------------
    print('Loading model stamps ...')
    model_data = []
    for m in MODELS:
        # look up grid parameters by tag -- fills sd_emb and r_be_arcsec
        # automatically so config only needs the tag and stamp_files
        ijk = m['tag'][1:].split('j'); _i = int(ijk[0])
        _jk = ijk[1].split('k');      _j = int(_jk[0]); _k = int(_jk[1])
        _gm = (_GRID['i']==_i) & (_GRID['j']==_j) & (_GRID['k']==_k)
        if not _gm.any():
            raise ValueError(f'Model {m["tag"]} not found in grid catalog.')
        grid_params = dict(
            SD_emb  = float(_GRID['SD_emb'] [_gm][0]),
            T_BE    = float(_GRID['T_BE']   [_gm][0]),
            rho_BE  = float(_GRID['rho_BE'] [_gm][0]),
            M_BE    = float(_GRID['M_BE']   [_gm][0]),
            R_BE_as = float(_GRID['R_BE_as'][_gm][0]),
        )
        # sd_emb and r_be_arcsec: use grid values unless explicitly overridden
        sd_emb      = m.get('sd_emb',      grid_params['SD_emb'])
        r_be_arcsec = m.get('r_be_arcsec', grid_params['R_BE_as'])
        if 'sd_emb' in m and abs(m['sd_emb'] - grid_params['SD_emb']) / grid_params['SD_emb'] > 0.01:
            print(f'  WARNING: {m["tag"]} config sd_emb={m["sd_emb"]:.2e} '
                  f'differs from grid SD_emb={grid_params["SD_emb"]:.2e}')
        if 'r_be_arcsec' in m and abs(m['r_be_arcsec'] - grid_params['R_BE_as']) > 0.1:
            print(f'  WARNING: {m["tag"]} config r_be_arcsec={m["r_be_arcsec"]:.2f}" '
                  f'differs from grid R_BE_as={grid_params["R_BE_as"]:.2f}"')

        # the observed size of the model, FWHMSDbs, which governs selection,
        # separation and the size class in version 3; R_BE is retained only
        # for the stamp geometry and for the truth table
        fwhm_arcsec = m.get('fwhm_as')
        if fwhm_arcsec is None:
            _fw = _grid_column('FWHMSD' + STAMP_SUFFIX, len(_GRID['M_BE']))
            fwhm_arcsec = float(_fw[_gm][0])
        stamp_size = None
        for b in inject.BANDS:
            if m['stamp_files'][b] is not None:
                stamp_size = fits.getdata(m['stamp_files'][b]).shape[0]
                break
        if stamp_size is None:
            raise ValueError(f'Model {m["tag"]}: all stamp files are None.')
        Ibs = {}
        for b in inject.BANDS:
            if m['stamp_files'][b] is not None:
                Ibs[b] = fits.getdata(m['stamp_files'][b]).astype(float)
            else:
                Ibs[b] = np.zeros((stamp_size, stamp_size))
        h = stamp_size // 2
        # Convolved footprint mask: pixels >= 1/100 of stamp peak, per band.
        # Used for both bg interpolation in inject_model and saved .foots images.
        mask_all = {}
        for b in inject.BANDS:
            I_b  = Ibs[b]
            peak = I_b.max()
            mask_all[b] = (I_b >= peak / 100.0).astype(float) if peak > 0 \
                          else np.zeros_like(I_b)
        sd_stamp = None
        if m.get('surfdens_stamp'):
            sd_stamp = fits.getdata(m['surfdens_stamp']).astype(float)
        model_data.append(dict(tag=m['tag'], sd_emb=sd_emb,
                               r_be_arcsec=r_be_arcsec,
                               fwhm_arcsec=fwhm_arcsec,
                               sigma_target=m.get('sigma_target'),
                               sigma_targets=m.get('sigma_targets', []),
                               Ibs=Ibs, mask=mask_all,
                               stamp_halfwidth=h,
                               sd_stamp=sd_stamp,
                               n_cores=m.get('n_cores', N_CORES),
                               grid=grid_params))
        peaks = {b: Ibs[b].max() for b in ['160','250','350','500']}
        print(f'  {m["tag"]:12s}  SD_emb={sd_emb:.2e}'
              f'  R_BE={r_be_arcsec:.2f}"'
              f'  FWHM_SD={fwhm_arcsec:.2f}"'
              f'  M_BE={grid_params["M_BE"]:.4f}'
              f'  250um peak={peaks["250"]:.3f} MJy/sr')

    # Place the models that are hardest to fit first, which means sorting by
    # the SAME radius that governs their exclusion of others, namely
    # model_radius_as, the larger of the true footprint R_BE and the observed
    # footprint.  Sorting by the observed size alone would put a concentrated,
    # large-xi_max model near the end of the queue, because its half-maximum
    # width is small, even though its exclusion radius is among the largest in
    # the set; by the time its turn came the field would be too crowded to
    # accept it, and it would drop out of the injection altogether.  Ties are
    # broken by sd_emb descending, since denser-cloud models have fewer valid
    # positions.
    model_data.sort(key=lambda md: (-model_radius_as(md['fwhm_arcsec'],
                                                     md['r_be_arcsec'],
                                                     md['tag']),
                                    -md['sd_emb']))
    if len(model_data) > 1:
        _r0 = model_radius_as(model_data[0]['fwhm_arcsec'],
                              model_data[0]['r_be_arcsec'],
                              model_data[0]['tag'])
        _r1 = model_radius_as(model_data[-1]['fwhm_arcsec'],
                              model_data[-1]['r_be_arcsec'],
                              model_data[-1]['tag'])
        print(f'  Sorted by exclusion radius, descending: '
              f'{model_data[0]["tag"]} ({_r0:.1f}")'
              f' ... {model_data[-1]["tag"]} ({_r1:.1f}")')

    # ------------------------------------------------------------------
    # 3. Find valid positions for each model and choose N_CORES each,
    #    with global separation (no two cores from any model closer than
    #    MIN_SEP_ARCSEC).
    # ------------------------------------------------------------------
    # Nominal separation criterion, reported and recorded in the truth-table
    # header.  It does NOT govern placement: the binding criterion is the
    # pairwise test below, which requires the centres of two models of the same
    # size class to be at least SEP_FACTOR times the sum of their convolved
    # radii apart, each radius being sqrt((FWHMSDbs/2)^2 + BEAM500^2).
    #
    # Version 2 contained an "if False:" clause here whose else-branch
    # overwrote the computed value with MIN_SEP_ARCSEC unconditionally.  In
    # single-model mode that silently replaced the beam criterion by the
    # configuration value, and in the mass-function mode of version 3, where
    # MIN_SEP_ARCSEC is None by construction, it raised a TypeError at the
    # print statement.  The dead clause is removed.
    if MIN_SEP_ARCSEC is None:
        # the 500 micron beam is sufficient to keep convolved models from
        # overlapping and is far less restrictive than a criterion scaled to
        # the largest model radius
        _min_sep = BEAM500
        print('  nominal separation criterion = %.1f" (500 um beam); '
              'placement is governed by the pairwise test on observed size'
              % _min_sep)
    else:
        _min_sep = float(MIN_SEP_ARCSEC)
        print('  nominal separation criterion = %.1f" (MIN_SEP_ARCSEC)'
              % _min_sep)
    print('Finding valid positions ...')
    foots     = fits.getdata(FOOTS_PATH).astype(float)
    forbidden = (foots > 0) if AVOID_REAL_FOOTPRINTS \
        else np.zeros(foots.shape, dtype=bool)
    if AVOID_REAL_FOOTPRINTS:
        _vprint('  centers of injected cores must clear the footprints of the '
                'real sources by %.1f arcsec; the footprints themselves cover '
                '%.1f%% of the field'
                % (FOOTPRINT_MARGIN_AS, 100.0 * np.mean(foots > 0)))
    else:
        _vprint('  real-source footprints are NOT excluded from placement')
    rng = np.random.default_rng(RANDOM_SEED)

    all_positions = []   # list of (model_index, y, x)
    used_centers  = []   # (y, x, convolved radius, R_BE) per placed core

    for mi, md in enumerate(model_data):
        valid = inject.valid_placement_mask(
            field,
            sigma_cloud=md['sd_emb'],
            R_BE_arcsec=md['r_be_arcsec'],
            sqrt2_window=True,
            forbidden=forbidden,
            stamp_halfwidth=md['stamp_halfwidth'],
            window=SIGMA_WINDOW,
            forbid_margin_as=(real_source_margin_as(md['fwhm_arcsec'],
                                                    md['r_be_arcsec'],
                                                    md['tag'])
                              if AVOID_REAL_FOOTPRINTS else None),
            # the column is averaged over the observed size of the model, not
            # over R_BE: a node with R_BE = 300 arcsec and FWHMSDbs = 35 arcsec
            # occupies the sky like a 35 arcsec source, and averaging over
            # 300 arcsec would smooth away the very structure the window is
            # meant to select
            local_average_radius_as=md['fwhm_arcsec'],
        )
        print(f'  {md["tag"]:12s}  valid pixels={valid.sum()}', end='')
        ys, xs = np.where(valid)
        if len(ys) == 0:
            print(f'  -- WARNING: no valid positions, skipping')
            continue
        # prefer positions whose local column is closest to the one drawn
        # Each core of this node has its own target column, drawn from the real
        # source it imitates.  Placing them all near the node's median column,
        # as version 2 did, collapses the spread of columns within a node: with
        # 79 nodes carrying about 8 cores each, the injected sample then had a
        # rank correlation of contrast on column of 0.258 against 0.507 for the
        # real sources.  Here the cores of a node are handled one at a time,
        # each steered to the column it was actually given.
        _lsig_map = inject.local_sigma(
            field['sigma'], md['fwhm_arcsec'] / inject.PIX_ARCSEC)
        _lsig = _lsig_map[ys, xs]
        _my_targets = list(md.get('sigma_targets') or [])
        n_want = md.get('n_cores', N_CORES)   # per-model override or global default
        if not _my_targets:
            _my_targets = [md.get('sigma_target') or md['sd_emb']] * n_want
        while len(_my_targets) < n_want:
            _my_targets.append(_my_targets[-1])
        _jitter = 1e-6 * rng.random(len(_lsig))
        # Separation = 2 * convolved radius = 2*sqrt(R_BE^2 + beam_radius^2)
        # ensures convolved model images do not overlap.  BEAM500 is the
        # 500um beam radius in arcsec (the largest beam, most conservative).
        import math
        # Version 3: the radius that must not overlap is set by the size the
        # model actually presents on the sky, taken as its half-maximum radius
        # FWHMSDbs / 2 added in quadrature with the 500 micron beam radius, and
        # no longer by R_BE.  Using R_BE gave a node of FWHMSDbs = 35 arcsec an
        # exclusion radius of 300 arcsec, which is why a handful of large-R_BE
        # models exhausted the usable area of the field.
        _rad = model_radius_as(md['fwhm_arcsec'], md['r_be_arcsec'],
                               md['tag'])                              # arcsec
        found  = 0
        _taken = np.zeros(len(ys), dtype=bool)
        for _tgt in _my_targets[:n_want]:
            # candidate positions for THIS core, nearest in the local column
            # to the column drawn for it
            if not (_tgt and _tgt > 0):
                _tgt = md['sd_emb']
            _key = np.where(_lsig > 0,
                            np.abs(np.log10(np.maximum(_lsig, 1e-30) / _tgt)),
                            9.0) + _jitter
            _key = np.where(_taken, np.inf, _key)
            order = np.argsort(_key)
            for idx in order:
                if not np.isfinite(_key[idx]):
                    break
                y, x = int(ys[idx]), int(xs[idx])
                if len(used_centers):
                    _uc = np.asarray(used_centers, dtype=float)
                    _smin = np.array([
                        min_separation_as(_rad, r)
                        for r in _uc[:, 2]]) / inject.PIX_ARCSEC + 1.0
                    _d2 = (y - _uc[:, 0])**2 + (x - _uc[:, 1])**2
                    _apply = np.array([
                        separation_applies(md['fwhm_arcsec'], f)
                        for f in _uc[:, 3]])
                    _ok = np.all(_d2[_apply] >= (_smin * _smin)[_apply])
                else:
                    _ok = True
                if not _ok:
                    _taken[idx] = True
                    continue
                _taken[idx] = True
                used_centers.append((y, x, _rad, md['fwhm_arcsec']))
                all_positions.append((mi, y, x))
                # mark as forbidden for subsequent models, on the same
                # size-class rule as the pairwise test above
                if (MAX_FOOTPRINT_OVERLAP is None
                        and OVERLAP_FREE_FWHM_AS is not None
                        and md['fwhm_arcsec'] > OVERLAP_FREE_FWHM_AS):
                    r = 0
                else:
                    r = int(round(0.5 * min_separation_as(_rad, _rad)
                                  / inject.PIX_ARCSEC))
                if r > 0:
                    y0,y1 = max(0,y-r), min(field['shape'][0],y+r+1)
                    x0,x1 = max(0,x-r), min(field['shape'][1],x+r+1)
                    yy,xx  = np.ogrid[y0-y:y1-y, x0-x:x1-x]
                    forbidden[y0:y1, x0:x1] |= (xx**2+yy**2 < r**2)
                found += 1
                break
        print(f'  -> placed {found}/{n_want}')

    print(f'  Total placed: {len(all_positions)} cores')

    if CONTROL_ISOLATED and len(all_positions) > 1:
        # Keep, in placement order, only cores whose radius overlaps no core
        # already kept, the radius being model_radius_as, the larger of the
        # true footprint R_BE and the observed footprint.
        _kept, _kx, _ky, _kr = [], [], [], []
        for _entry in all_positions:
            _mi, _y, _x = _entry
            _r = model_radius_as(model_data[_mi]['fwhm_arcsec'],
                                 model_data[_mi]['r_be_arcsec'],
                                 model_data[_mi]['tag'])
            if _kx:
                _d = np.hypot(np.asarray(_kx) - _x,
                              np.asarray(_ky) - _y) * inject.PIX_ARCSEC
                if np.any(_d < (_r + np.asarray(_kr))):
                    continue
            _kept.append(_entry); _kx.append(_x); _ky.append(_y); _kr.append(_r)
        print(f'  CONTROL_ISOLATED: keeping the {len(_kept)} of '
              f'{len(all_positions)} cores whose footprints overlap no other '
              f'kept core')
        print(f'    every kept core is at the same position, with the same '
              f'model, as in the companion run of the same seed')
        all_positions = _kept

    # ------------------------------------------------------------------
    # 4. Inject all cores
    # ------------------------------------------------------------------
    print('Injecting (background: getsf power-9 interpolation) ...')
    current = {b: field['img'][b].copy() for b in inject.BANDS}
    truth   = []
    core_id = 0

    for mi, cy, cx in all_positions:
        md = model_data[mi]
        core_id += 1
        updated = inject.inject_model(
            {'img': current, 'omask': field['omask'],
             'sigma': field['sigma'], 'coverage': field['coverage'],
             'shape': field['shape']},
            center=(cy, cx),
            Ibs=md['Ibs'],
            mask=md['mask'],
            flatten=(FLATTEN_BACKGROUND
                     and (FLATTEN_MAX_FWHM_AS is None
                          or md['fwhm_arcsec'] <= FLATTEN_MAX_FWHM_AS)),
        )
        for b in inject.BANDS:
            current[b] = updated[b]
        # local_Sigma = mean background column over a disk of radius 2*R_BE
        # (2x the core radius samples the embedding cloud, matching the scale
        # that getsf uses for its background estimate in the surrounding rim;
        # use the pre-injection sigma map so the model's own column is excluded)
        h_sd = md['stamp_halfwidth']
        y0s, y1s = max(0, cy-h_sd), min(field['shape'][0], cy+h_sd+1)
        x0s, x1s = max(0, cx-h_sd), min(field['shape'][1], cx+h_sd+1)
        yy_d, xx_d = np.ogrid[y0s-cy:y1s-cy, x0s-cx:x1s-cx]
        R_disk_pix = 2.0 * md['r_be_arcsec'] / inject.PIX_ARCSEC
        disk_mask  = (xx_d**2 + yy_d**2) <= R_disk_pix**2
        # the surface-density map as it stands now, if that band is being
        # injected into, so that local_Sigma describes the background this
        # core really sits on rather than the pristine field
        _sig_map = current.get('000', field['sigma'])
        if _sig_map.shape != field['sigma'].shape:
            _sig_map = field['sigma']
        sigma_patch = _sig_map[y0s:y1s, x0s:x1s]
        valid_px    = disk_mask & (sigma_patch > 0)
        local_sig   = float(sigma_patch[valid_px].mean()) if valid_px.any() else _sig_map[cy, cx]
        patch      = (current['250'][cy-5:cy+6, cx-5:cx+6]
                      - field['img']['250'][cy-5:cy+6, cx-5:cx+6])
        # with flattening, patch.max() is the NET change to the map, which
        # goes negative where the interpolation removed more than the model
        # added; report the model's own peak instead
        peak_added = float(np.nanmax(md['Ibs']['250'])) \
            if isinstance(md.get('Ibs'), dict) and '250' in md['Ibs'] \
            else patch.max()
        truth.append((core_id, md['tag'], cx+1, cy+1, local_sig, md['grid'],
                      md['fwhm_arcsec']))
        print(f'  core {core_id:2d} ({md["tag"]:12s}): '
              f'x={cx+1:4d}  y={cy+1:4d}  '
              f'local_Sigma={local_sig:.3e} cm-2  '
              f'250um peak added = {peak_added:.2f} MJy/sr')


    # ------------------------------------------------------------------
    # 5. Write output band images  (field + injected sources)
    # ------------------------------------------------------------------
    def _write_fits(arr, path, ref_hdr, bunit=None, wave=None):
        """Write array to FITS preserving WCS from ref_hdr.
        If wave is given (microns), set WAVE keyword explicitly."""
        hdu = fits.PrimaryHDU(arr.astype(np.float32), header=ref_hdr)
        hdu.header['BZERO']  = 0.0
        hdu.header['BSCALE'] = 1.0
        if bunit is not None:
            hdu.header['BUNIT'] = bunit
        if wave is not None:
            hdu.header['WAVE'] = wave
        hdu.writeto(path, overwrite=True)
        # set BZERO/BSCALE in a second pass (ensures no scaling applied on read)
        with fits.open(path, mode='update') as hf:
            hf[0].header['BZERO']  = 0.0
            hf[0].header['BSCALE'] = 1.0
            if wave is not None:
                hf[0].header['WAVE'] = wave

    def _make_omask(img):
        """1.0 inside valid coverage, 0.0 in the border strip of zero pixels."""
        from scipy.ndimage import binary_erosion as _be
        return _be(img != 0, border_value=0).astype(np.float32)

    print('Writing output images ...')
    for b in inject.BANDS:
        if b not in IMG_PATHS: continue  # skip if band not configured
        src_hdr  = fits.getheader(IMG_PATHS[b])
        out_path = os.path.join(OUT_DIR, f'inj_{SET_TAG}.{b}um.fits')
        arr = current[b].astype(np.float32)
        _bwave = {'000':0,'070':70,'160':160,'250':250,'350':350,'500':500}.get(b, 0)
        _write_fits(arr, out_path, src_hdr, wave=_bwave)
        src_hdr['HISTORY'] = f'Injected {SET_TAG} x{len(all_positions)} seed={RANDOM_SEED}'
        print(f'  {out_path}')
        out_omask = out_path.replace('.fits', '.omask.fits')
        _write_fits(_make_omask(arr), out_omask, src_hdr, wave=_bwave)
        print(f'  {out_omask}')

    # ------------------------------------------------------------------
    # 5b. Write source-only images (zero background, stamps only)
    # ------------------------------------------------------------------
    print('Writing source-only images ...')
    ny, nx = field['shape']
    for b in inject.BANDS:
        if b not in IMG_PATHS: continue
        src_hdr  = fits.getheader(IMG_PATHS[b])
        src_only = np.zeros((ny, nx), dtype=np.float32)
        for mi, cy, cx in all_positions:
            md  = model_data[mi]
            I   = md['Ibs'][b]
            msk = md['mask'][b] > 0
            h   = md['stamp_halfwidth']
            y0, y1 = cy - h, cy + h + 1
            x0, x1 = cx - h, cx + h + 1
            if y0 >= 0 and y1 <= ny and x0 >= 0 and x1 <= nx:
                src_only[y0:y1, x0:x1] += I.astype(np.float32)  # full stamp, no mask
        out_src = os.path.join(OUT_DIR, f'src_{SET_TAG}.{b}um.fits')
        _bwave  = {'000':0,'070':70,'160':160,'250':250,'350':350,'500':500}.get(b, 0)
        _write_fits(src_only, out_src, src_hdr, wave=_bwave)
        print(f'  {out_src}')

    # source-only surfdens (zero background, column stamps only)

    # ------------------------------------------------------------------
    # 5c. Write footprint mask images (1 inside R_BE disk, 0 outside)
    #     One per band + surfdens; all injected cores accumulated.
    # ------------------------------------------------------------------
    print('Writing footprint mask images ...')
    foot_bands = inject.BANDS if HIRES_SURFDENS_PATH and os.path.exists(HIRES_SURFDENS_PATH)                  else inject.BANDS
    foot_imgs  = {b: np.zeros((ny, nx), dtype=np.float32) for b in inject.BANDS}
    for mi, cy, cx in all_positions:
        md  = model_data[mi]
        h   = md['stamp_halfwidth']
        y0, y1 = cy - h, cy + h + 1
        x0, x1 = cx - h, cx + h + 1
        if y0 >= 0 and y1 <= ny and x0 >= 0 and x1 <= nx:
            for b in inject.BANDS:
                cmsk = md['mask'][b].astype(np.float32)
                foot_imgs[b][y0:y1, x0:x1] = np.maximum(
                    foot_imgs[b][y0:y1, x0:x1], cmsk)
    for b in inject.BANDS:
        if b not in IMG_PATHS: continue
        src_hdr = fits.getheader(IMG_PATHS[b])
        out_fp  = os.path.join(OUT_DIR, f'inj_{SET_TAG}.{b}um.foots.fits')
        _write_fits(foot_imgs[b], out_fp, src_hdr, wave=_bwave)
        print(f'  {out_fp}')

    # ------------------------------------------------------------------
    # 6. Write truth table
    # ------------------------------------------------------------------
    out_truth = os.path.join(OUT_DIR, f'inj_{SET_TAG}_truth.txt')
    hdr = ('# id    model         x_pix  y_pix  local_Sigma  SD_emb       T_BE   '
           'rho_BE       M_BE    R_BE_as  FWHM_SD  scale')
    with open(out_truth, 'w') as f:
        f.write(f'# Injection truth table -- {SET_TAG}  seed={RANDOM_SEED}\n')
        for _ln in _V2_LOG:
            f.write('# %s\n' % _ln.strip())
        f.write(f'# sep_criterion={_min_sep:.1f}"  scale_factor={SCALE_FACTOR:.4g}  '
                f'local_Sigma/SD_emb in cm-2  T_BE in K  rho_BE in cm-3  M_BE in Msun  '
                f'R_BE_as in arcsec (truncation radius of the sphere)  '
                f'FWHM_SD in arcsec (observed major axis at half maximum of the '
                f'model in the surface-density image, FWHMSDbs)\n')
        f.write(hdr + '\n')
        f.write('#' + '-' * (len(hdr) - 1) + '\n')
        for cid, tag, xp, yp, sig, gp, fw in truth:
            f.write(f'  {cid:03d}  {tag:12s}'
                    f'  {xp:5d}  {yp:5d}'
                    f'  {sig:11.3e}  {gp["SD_emb"]:11.3e}'
                    f'  {gp["T_BE"]:6.2f}  {gp["rho_BE"]:11.3e}'
                    f'  {gp["M_BE"]:6.4f}  {gp["R_BE_as"]:7.2f}'
                    f'  {fw:7.2f}  {SCALE_FACTOR:.4g}\n')
    print(f'  {out_truth}')

    print('Done.')


if __name__ == '__main__':
    main()
