#!/usr/bin/env python
"""
run_inject.py -- inject BE-sphere models into Herschel maps.

DO NOT EDIT THIS FILE.  All settings live in a config file.

USAGE
-----
  python -B run_inject.py                        # uses inject_config.py
  python -B run_inject.py inject_config_set3     # uses inject_config_set3.py
  python -B run_inject.py inject_config_i1j2k4   # single-model config

CONFIG FILE FORMATS
-------------------
Multi-model (preferred for Tier-2):
  SET_TAG = 'set3'
  MODELS  = [ dict(tag=..., sd_emb=..., r_be_arcsec=..., stamp_files={...}), ... ]
  Separation computed automatically: sqrt((2*R_BE_max)^2 + 36.3^2).

Single-model (backward compatible):
  MODEL_TAG, SD_EMB, R_BE_ARCSEC, STAMP_FILES, MIN_SEP_ARCSEC

Both formats share field paths via inject_config_field.py (on PYTHONPATH
or in the same directory as this script / its Python/ subdirectory).

DEPENDENCIES
------------
  pip install numpy astropy scipy
"""

import sys, os, importlib, importlib.util
import numpy as np
from astropy.io import fits

# -----------------------------------------------------------------------
# Search order: cwd -> script/Python/ -> script dir -> PYTHONPATH
# -----------------------------------------------------------------------
_here    = os.path.dirname(os.path.abspath(__file__))
_here_py = os.path.join(_here, 'Python')
_cwd     = os.getcwd()
sys.path.insert(0, _here)
sys.path.insert(0, _here_py)
sys.path.insert(0, _cwd)

try:
    from fit_mass import load_catalog as _load_grid
except ModuleNotFoundError:
    raise ModuleNotFoundError(
        'fit_mass.py not found. Place it in SCRIPTS/Python/ alongside inject.py.')

def _find_catalog(name):
    """Search for catalog file in cwd, then script Python/ dir, then script dir."""
    for d in [_cwd, _here_py, _here]:
        p = os.path.join(d, name)
        if os.path.exists(p):
            return p
    raise FileNotFoundError(
        f'"{name}" not found in cwd, {_here_py}, or {_here}.\n'
        f'Set BES_CATALOG in inject_config_field.py or place the file in SCRIPTS/Python/')

_config_arg  = sys.argv[1] if len(sys.argv) > 1 else 'inject_config'
_config_name = os.path.splitext(os.path.basename(_config_arg))[0]
_config_file = os.path.join(_cwd, _config_name + '.py')

if not os.path.exists(_config_file):
    print(f'ERROR: config file "{_config_name}.py" not found in:')
    print(f'  {_cwd}')
    print(f'  Config files must have the .py extension.')
    print(f'  If your file has no extension, rename it:')
    print(f'    mv {_config_name} {_config_name}.py')
    sys.exit(1)

try:
    _spec = importlib.util.spec_from_file_location(_config_name, _config_file)
    _cfg  = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_cfg)
except Exception as _e:
    print(f'ERROR: failed to load "{_config_name}.py": {_e}')
    print(f'  helper modules searched in: {_here_py}  and  {_here}')
    sys.exit(1)

print(f'Config: {_config_name}  ({_config_file})')

import inject

# load model grid catalog -- path set via BES_CATALOG in the config file;
# falls back to searching cwd and SCRIPTS/Python/ if not set.
_bes_catalog_path = getattr(_cfg, 'BES_CATALOG', None) or _find_catalog('bes_model_params_catalog')
_GRID = _load_grid(_bes_catalog_path)
print(f'Grid catalog: {_bes_catalog_path}')

# -----------------------------------------------------------------------
# Normalise config: support both single-model and multi-model formats
# -----------------------------------------------------------------------
BEAM500 = 36.3   # arcsec, 500um beam -- used for separation criterion


def _stamp_files_from_tag(tag, root):
    """Build stamp_files dict and surfdens_stamp path from a model tag and
    STAMP_ROOT, using the directory tree:
        <root>/cSD_{i:02d}/tBE_{j:02d}/{k:02d}/nc.<band>um.bs.<res>x0.rs3p0as.fits

    Band beam tokens (fixed Herschel PSF):
        160 um -> r13p5,  250 um -> r18p2,
        350 um -> r24p9,  500 um -> r36p3
    070 um is always None.  surfdens uses the 160 um token (r13p5).
    """
    import re
    m = re.fullmatch(r'i(\d+)j(\d+)k(\d+)', tag)
    if m is None:
        raise ValueError(f'Cannot parse model tag "{tag}": expected iNjMkK')
    i, j, k = int(m.group(1)), int(m.group(2)), int(m.group(3))
    subdir = os.path.join(root, f'cSD_{i:02d}', f'tBE_{j:02d}', f'{k:02d}')
    res = {'000': 'r13p5', '160': 'r13p5', '250': 'r18p2', '350': 'r24p9', '500': 'r36p3'}
    stamp_files = {'070': None}
    for b, r in res.items():
        if b == '000':
            stamp_files[b] = os.path.join(subdir, 'nc.surfdens.bs.r13p5x0.rs3p0as.fits')
        else:
            stamp_files[b] = os.path.join(subdir, f'nc.{b}um.bs.{r}x0.rs3p0as.fits')
    return stamp_files


def _normalise_model_entry(entry, stamp_root):
    """Accept a model entry as a bare tag string, a tag-only dict, or a full
    dict with stamp_files.  In the first two cases stamp paths are built
    automatically from STAMP_ROOT; a full dict is returned unchanged."""
    if isinstance(entry, str):
        entry = dict(tag=entry)
    if 'stamp_files' not in entry:
        if stamp_root is None:
            raise ValueError(
                f'Model "{entry["tag"]}" has no stamp_files and STAMP_ROOT is not set.')
        sf = _stamp_files_from_tag(entry['tag'], stamp_root)
        entry = dict(entry)
        entry['stamp_files'] = sf
    return entry

if hasattr(_cfg, 'MODELS'):
    # --- multi-model format ---
    SET_TAG  = _cfg.SET_TAG
    STAMP_ROOT = getattr(_cfg, 'STAMP_ROOT', None)
    MODELS     = [_normalise_model_entry(m, STAMP_ROOT) for m in _cfg.MODELS]
    N_CORES  = _cfg.N_CORES
    RANDOM_SEED     = _cfg.RANDOM_SEED
    OUT_DIR         = _cfg.OUT_DIR
    IMG_PATHS       = _cfg.IMG_PATHS
    OMASK_PATHS     = _cfg.OMASK_PATHS
    SIGMA_PATH      = _cfg.SIGMA_PATH
    SIGMA_OMASK_PATH= _cfg.SIGMA_OMASK_PATH
    FOOTS_PATH      = _cfg.FOOTS_PATH
    HIRES_SURFDENS_PATH = getattr(_cfg, 'HIRES_SURFDENS_PATH', None)
    SCALE_FACTOR        = getattr(_cfg, 'SCALE_FACTOR', 1.0)
    R_BE_MAX_AS         = getattr(_cfg, 'R_BE_MAX_AS', None)  # skip models with R_BE > this (arcsec)
    if SCALE_FACTOR != 1.0: SET_TAG = SET_TAG + f'_x{SCALE_FACTOR:.4g}'
    # Treat surfdens as band '000': plug into IMG_PATHS/OMASK_PATHS so all
    # band loops handle it uniformly.
    if HIRES_SURFDENS_PATH:
        IMG_PATHS['000']   = HIRES_SURFDENS_PATH
        OMASK_PATHS['000'] = SIGMA_OMASK_PATH
    # MIN_SEP_ARCSEC computed in main() after r_be_arcsec is filled from grid
    MIN_SEP_ARCSEC = None
    print(f'  Multi-model set "{SET_TAG}": {len(MODELS)} models')
else:
    # --- single-model format (backward compatible) ---
    SET_TAG  = _cfg.MODEL_TAG
    MODELS   = [dict(
        tag         = _cfg.MODEL_TAG,
        sd_emb      = _cfg.SD_EMB,
        r_be_arcsec = _cfg.R_BE_ARCSEC,
        stamp_files = _cfg.STAMP_FILES,
        surfdens_stamp = None,
    )]
    N_CORES          = _cfg.N_CORES
    MIN_SEP_ARCSEC   = _cfg.MIN_SEP_ARCSEC
    RANDOM_SEED      = _cfg.RANDOM_SEED
    OUT_DIR          = _cfg.OUT_DIR
    IMG_PATHS        = _cfg.IMG_PATHS
    OMASK_PATHS      = _cfg.OMASK_PATHS
    SIGMA_PATH       = _cfg.SIGMA_PATH
    SIGMA_OMASK_PATH = _cfg.SIGMA_OMASK_PATH
    FOOTS_PATH       = _cfg.FOOTS_PATH
    HIRES_SURFDENS_PATH = getattr(_cfg, 'HIRES_SURFDENS_PATH', None)
    SCALE_FACTOR        = getattr(_cfg, 'SCALE_FACTOR', 1.0)
    if SCALE_FACTOR != 1.0: SET_TAG = SET_TAG + f'_x{SCALE_FACTOR:.4g}'
    if HIRES_SURFDENS_PATH:
        IMG_PATHS['000']   = HIRES_SURFDENS_PATH
        OMASK_PATHS['000'] = SIGMA_OMASK_PATH
    print(f'  Single-model: {SET_TAG}')


def main():

    # ------------------------------------------------------------------
    # 0. File inventory
    # ------------------------------------------------------------------
    def _info(label, path):
        abspath = os.path.abspath(path)
        if not os.path.exists(abspath):
            print(f'  {label:30s}  MISSING  {abspath}'); return
        d = fits.getdata(abspath).astype(float)
        print(f'  {label:30s}  shape={d.shape}  '
              f'min={d.min():.3g}  max={d.max():.3g}  {abspath}')

    print('File inventory:')
    for b in inject.BANDS:
        _info(f'img {b}um', IMG_PATHS[b])
    _info('sigma map',  SIGMA_PATH)
    _info('sigma omask',SIGMA_OMASK_PATH)
    _info('footprints', FOOTS_PATH)
    for m in MODELS:
        for b,p in m['stamp_files'].items():
            if p: _info(f'stamp {m["tag"]} {b}um', p)
    print()

    # ------------------------------------------------------------------
    # 1. Load field
    # ------------------------------------------------------------------
    print('Loading field maps ...')
    field = inject.load_field(
        IMG_PATHS, OMASK_PATHS,
        sigma_path=SIGMA_PATH,
        sigma_omask_path=SIGMA_OMASK_PATH,
    )
    print(f'  field shape: {field["shape"]}')
    print(f'  coverage pixels: {field["coverage"].sum()}')

    if SCALE_FACTOR != 1.0:
        print(f'  Scaling all field images and sigma map by {SCALE_FACTOR:.4g} ...')
        for b in inject.BANDS:
            field['img'][b] = field['img'][b] * SCALE_FACTOR
        field['sigma'] = field['sigma'] * SCALE_FACTOR
        print(f'  Sigma range after scaling: {field["sigma"][field["sigma"]>0].min():.2e}'
              f' -- {field["sigma"].max():.2e} cm-2')

    # ------------------------------------------------------------------
    # 2. Load stamps for each model
    # ------------------------------------------------------------------
    print('Loading model stamps ...')
    model_data = []
    for m in MODELS:
        # look up grid parameters by tag -- fills sd_emb and r_be_arcsec
        # automatically so config only needs the tag and stamp_files
        ijk = m['tag'][1:].split('j'); _i = int(ijk[0])
        _jk = ijk[1].split('k');      _j = int(_jk[0]); _k = int(_jk[1])
        _gm = (_GRID['i']==_i) & (_GRID['j']==_j) & (_GRID['k']==_k)
        if not _gm.any():
            raise ValueError(f'Model {m["tag"]} not found in grid catalog.')
        grid_params = dict(
            SD_emb  = float(_GRID['SD_emb'] [_gm][0]),
            T_BE    = float(_GRID['T_BE']   [_gm][0]),
            rho_BE  = float(_GRID['rho_BE'] [_gm][0]),
            M_BE    = float(_GRID['M_BE']   [_gm][0]),
            R_BE_as = float(_GRID['R_BE_as'][_gm][0]),
        )
        # sd_emb and r_be_arcsec: use grid values unless explicitly overridden
        sd_emb      = m.get('sd_emb',      grid_params['SD_emb'])
        r_be_arcsec = m.get('r_be_arcsec', grid_params['R_BE_as'])
        if 'sd_emb' in m and abs(m['sd_emb'] - grid_params['SD_emb']) / grid_params['SD_emb'] > 0.01:
            print(f'  WARNING: {m["tag"]} config sd_emb={m["sd_emb"]:.2e} '
                  f'differs from grid SD_emb={grid_params["SD_emb"]:.2e}')
        if 'r_be_arcsec' in m and abs(m['r_be_arcsec'] - grid_params['R_BE_as']) > 0.1:
            print(f'  WARNING: {m["tag"]} config r_be_arcsec={m["r_be_arcsec"]:.2f}" '
                  f'differs from grid R_BE_as={grid_params["R_BE_as"]:.2f}"')

        if R_BE_MAX_AS is not None and r_be_arcsec > R_BE_MAX_AS:
            print(f'  SKIP {m["tag"]:12s}  R_BE={r_be_arcsec:.1f}" > R_BE_MAX_AS={R_BE_MAX_AS:.1f}"')
            continue
        stamp_size = None
        for b in inject.BANDS:
            if m['stamp_files'][b] is not None:
                stamp_size = fits.getdata(m['stamp_files'][b]).shape[0]
                break
        if stamp_size is None:
            raise ValueError(f'Model {m["tag"]}: all stamp files are None.')
        Ibs = {}
        for b in inject.BANDS:
            if m['stamp_files'][b] is not None:
                Ibs[b] = fits.getdata(m['stamp_files'][b]).astype(float)
            else:
                Ibs[b] = np.zeros((stamp_size, stamp_size))
        h = stamp_size // 2
        # Convolved footprint mask: pixels >= 1/100 of stamp peak, per band.
        # Used for both bg interpolation in inject_model and saved .foots images.
        mask_all = {}
        for b in inject.BANDS:
            I_b  = Ibs[b]
            peak = I_b.max()
            mask_all[b] = (I_b >= peak / 100.0).astype(float) if peak > 0 \
                          else np.zeros_like(I_b)
        sd_stamp = None
        if m.get('surfdens_stamp'):
            sd_stamp = fits.getdata(m['surfdens_stamp']).astype(float)
        model_data.append(dict(tag=m['tag'], sd_emb=sd_emb,
                               r_be_arcsec=r_be_arcsec,
                               Ibs=Ibs, mask=mask_all,
                               stamp_halfwidth=h,
                               sd_stamp=sd_stamp,
                               n_cores=m.get('n_cores', N_CORES),
                               grid=grid_params))
        peaks = {b: Ibs[b].max() for b in ['160','250','350','500']}
        print(f'  {m["tag"]:12s}  SD_emb={sd_emb:.2e}'
              f'  R_BE={r_be_arcsec:.2f}"'
              f'  M_BE={grid_params["M_BE"]:.4f}'
              f'  250um peak={peaks["250"]:.3f} MJy/sr')

    # sort largest R_BE first; break ties by sd_emb descending
    # (denser-cloud models have fewer valid positions so place them first)
    model_data.sort(key=lambda md: (-md['r_be_arcsec'], -md['sd_emb']))
    if len(model_data) > 1:
        print(f'  Sorted by R_BE desc: {model_data[0]["tag"]} ({model_data[0]["r_be_arcsec"]:.1f}")'
              f' ... {model_data[-1]["tag"]} ({model_data[-1]["r_be_arcsec"]:.1f}")')

    # ------------------------------------------------------------------
    # 3. Find valid positions for each model and choose N_CORES each,
    #    with global separation (no two cores from any model closer than
    #    MIN_SEP_ARCSEC).
    # ------------------------------------------------------------------
    # compute separation criterion now that r_be_arcsec is filled from grid
    if MIN_SEP_ARCSEC is None:
        R_max = max(md['r_be_arcsec'] for md in model_data)
        _min_sep = np.sqrt((2*R_max)**2 + BEAM500**2)
        print(f'  R_BE_max={R_max:.2f}"  separation criterion={_min_sep:.1f}"'
              f'  ({_min_sep/inject.PIX_ARCSEC:.1f} px)')
    else:
        _min_sep = MIN_SEP_ARCSEC
    print(f'Finding valid positions (sep >= {_min_sep:.1f}") ...')
    foots     = fits.getdata(FOOTS_PATH).astype(float)
    forbidden = foots > 0
    min_sep_pix = int(np.ceil(_min_sep / inject.PIX_ARCSEC))
    rng = np.random.default_rng(RANDOM_SEED)

    all_positions = []   # list of (model_index, y, x)
    used_centers  = []   # all placed centers for global separation check

    for mi, md in enumerate(model_data):
        valid = inject.valid_placement_mask(
            field,
            sigma_cloud=md['sd_emb'],
            R_BE_arcsec=md['r_be_arcsec'],
            sqrt2_window=True,
            forbidden=forbidden,
            stamp_halfwidth=md['stamp_halfwidth'],
        )
        print(f'  {md["tag"]:12s}  valid pixels={valid.sum()}', end='')
        ys, xs = np.where(valid)
        if len(ys) == 0:
            print(f'  -- WARNING: no valid positions, skipping')
            continue
        order  = rng.permutation(len(ys))
        n_want = md.get('n_cores', N_CORES)   # per-model override or global default
        # Separation = 2 * convolved radius = 2*sqrt(R_BE^2 + beam_radius^2)
        # ensures convolved model images do not overlap.  BEAM500 is the
        # 500um beam radius in arcsec (the largest beam, most conservative).
        import math
        _sep_this_pix = int(math.ceil(
            1.5 * 2.0 * math.sqrt(md['r_be_arcsec']**2 + BEAM500**2) / inject.PIX_ARCSEC)) + 1
        found  = 0
        for idx in order:
            if found >= n_want: break
            y, x = int(ys[idx]), int(xs[idx])
            s2 = _sep_this_pix ** 2
            if all((y-cy)**2 + (x-cx)**2 >= s2 for cy,cx in used_centers):
                used_centers.append((y, x))
                all_positions.append((mi, y, x))
                # also mark as forbidden for subsequent models
                r = md['stamp_halfwidth']
                y0,y1 = max(0,y-r), min(field['shape'][0],y+r+1)
                x0,x1 = max(0,x-r), min(field['shape'][1],x+r+1)
                yy,xx  = np.ogrid[y0-y:y1-y, x0-x:x1-x]
                forbidden[y0:y1, x0:x1] |= (xx**2+yy**2 < r**2)
                found += 1
        print(f'  -> placed {found}/{n_want}')

    print(f'  Total placed: {len(all_positions)} cores')

    # ------------------------------------------------------------------
    # 4. Inject all cores
    # ------------------------------------------------------------------
    print('Injecting (background: getsf power-9 interpolation) ...')
    current = {b: field['img'][b].copy() for b in inject.BANDS}
    truth   = []
    core_id = 0

    for mi, cy, cx in all_positions:
        md = model_data[mi]
        core_id += 1
        updated = inject.inject_model(
            {'img': current, 'omask': field['omask'],
             'sigma': field['sigma'], 'coverage': field['coverage'],
             'shape': field['shape']},
            center=(cy, cx),
            Ibs=md['Ibs'],
            mask=md['mask'],
            flatten=True,
        )
        for b in inject.BANDS:
            current[b] = updated[b]
        # local_Sigma = mean background column over a disk of radius 2*R_BE
        # (2x the core radius samples the embedding cloud, matching the scale
        # that getsf uses for its background estimate in the surrounding rim;
        # use the pre-injection sigma map so the model's own column is excluded)
        h_sd = md['stamp_halfwidth']
        y0s, y1s = max(0, cy-h_sd), min(field['shape'][0], cy+h_sd+1)
        x0s, x1s = max(0, cx-h_sd), min(field['shape'][1], cx+h_sd+1)
        yy_d, xx_d = np.ogrid[y0s-cy:y1s-cy, x0s-cx:x1s-cx]
        R_disk_pix = 2.0 * md['r_be_arcsec'] / inject.PIX_ARCSEC
        disk_mask  = (xx_d**2 + yy_d**2) <= R_disk_pix**2
        sigma_patch = field['sigma'][y0s:y1s, x0s:x1s]
        valid_px    = disk_mask & (sigma_patch > 0)
        local_sig   = float(sigma_patch[valid_px].mean()) if valid_px.any() else field['sigma'][cy, cx]
        patch      = (current['250'][cy-5:cy+6, cx-5:cx+6]
                      - field['img']['250'][cy-5:cy+6, cx-5:cx+6])
        peak_added = patch.max()
        truth.append((core_id, md['tag'], cx+1, cy+1, local_sig, md['grid']))
        print(f'  core {core_id:2d} ({md["tag"]:12s}): '
              f'x={cx+1:4d}  y={cy+1:4d}  '
              f'local_Sigma={local_sig:.3e} cm-2  '
              f'250um peak added = {peak_added:.2f} MJy/sr')


    # ------------------------------------------------------------------
    # 5. Write output band images  (field + injected sources)
    # ------------------------------------------------------------------
    def _write_fits(arr, path, ref_hdr, bunit=None, wave=None):
        """Write array to FITS preserving WCS from ref_hdr.
        If wave is given (microns), set WAVE keyword explicitly."""
        hdu = fits.PrimaryHDU(arr.astype(np.float32), header=ref_hdr)
        hdu.header['BZERO']  = 0.0
        hdu.header['BSCALE'] = 1.0
        if bunit is not None:
            hdu.header['BUNIT'] = bunit
        if wave is not None:
            hdu.header['WAVE'] = wave
        hdu.writeto(path, overwrite=True)
        # set BZERO/BSCALE in a second pass (ensures no scaling applied on read)
        with fits.open(path, mode='update') as hf:
            hf[0].header['BZERO']  = 0.0
            hf[0].header['BSCALE'] = 1.0
            if wave is not None:
                hf[0].header['WAVE'] = wave

    def _make_omask(img):
        """1.0 inside valid coverage, 0.0 in the border strip of zero pixels."""
        from scipy.ndimage import binary_erosion as _be
        return _be(img != 0, border_value=0).astype(np.float32)

    print('Writing output images ...')
    for b in inject.BANDS:
        if b not in IMG_PATHS: continue  # skip if band not configured
        src_hdr  = fits.getheader(IMG_PATHS[b])
        out_path = os.path.join(OUT_DIR, f'inj_{SET_TAG}.{b}um.fits')
        arr = current[b].astype(np.float32)
        _bwave = {'000':0,'070':70,'160':160,'250':250,'350':350,'500':500}.get(b, 0)
        _write_fits(arr, out_path, src_hdr, wave=_bwave)
        src_hdr['HISTORY'] = f'Injected {SET_TAG} x{len(all_positions)} seed={RANDOM_SEED}'
        print(f'  {out_path}')
        out_omask = out_path.replace('.fits', '.omask.fits')
        _write_fits(_make_omask(arr), out_omask, src_hdr, wave=_bwave)
        print(f'  {out_omask}')

    # ------------------------------------------------------------------
    # 5b. Write source-only images (zero background, stamps only)
    # ------------------------------------------------------------------
    print('Writing source-only images ...')
    ny, nx = field['shape']
    for b in inject.BANDS:
        if b not in IMG_PATHS: continue
        src_hdr  = fits.getheader(IMG_PATHS[b])
        src_only = np.zeros((ny, nx), dtype=np.float32)
        for mi, cy, cx in all_positions:
            md  = model_data[mi]
            I   = md['Ibs'][b]
            msk = md['mask'][b] > 0
            h   = md['stamp_halfwidth']
            y0, y1 = cy - h, cy + h + 1
            x0, x1 = cx - h, cx + h + 1
            if y0 >= 0 and y1 <= ny and x0 >= 0 and x1 <= nx:
                src_only[y0:y1, x0:x1] += I.astype(np.float32)  # full stamp, no mask
        out_src = os.path.join(OUT_DIR, f'src_{SET_TAG}.{b}um.fits')
        _bwave  = {'000':0,'070':70,'160':160,'250':250,'350':350,'500':500}.get(b, 0)
        _write_fits(src_only, out_src, src_hdr, wave=_bwave)
        print(f'  {out_src}')

    # source-only surfdens (zero background, column stamps only)

    # ------------------------------------------------------------------
    # 5c. Write footprint mask images (1 inside R_BE disk, 0 outside)
    #     One per band + surfdens; all injected cores accumulated.
    # ------------------------------------------------------------------
    print('Writing footprint mask images ...')
    foot_bands = inject.BANDS if HIRES_SURFDENS_PATH and os.path.exists(HIRES_SURFDENS_PATH)                  else inject.BANDS
    foot_imgs  = {b: np.zeros((ny, nx), dtype=np.float32) for b in inject.BANDS}
    for mi, cy, cx in all_positions:
        md  = model_data[mi]
        h   = md['stamp_halfwidth']
        y0, y1 = cy - h, cy + h + 1
        x0, x1 = cx - h, cx + h + 1
        if y0 >= 0 and y1 <= ny and x0 >= 0 and x1 <= nx:
            for b in inject.BANDS:
                cmsk = md['mask'][b].astype(np.float32)
                foot_imgs[b][y0:y1, x0:x1] = np.maximum(
                    foot_imgs[b][y0:y1, x0:x1], cmsk)
    for b in inject.BANDS:
        if b not in IMG_PATHS: continue
        src_hdr = fits.getheader(IMG_PATHS[b])
        out_fp  = os.path.join(OUT_DIR, f'inj_{SET_TAG}.{b}um.foots.fits')
        _write_fits(foot_imgs[b], out_fp, src_hdr, wave=_bwave)
        print(f'  {out_fp}')

    # ------------------------------------------------------------------
    # 6. Write truth table
    # ------------------------------------------------------------------
    out_truth = os.path.join(OUT_DIR, f'inj_{SET_TAG}_truth.txt')
    hdr = ('# id    model         x_pix  y_pix  local_Sigma  SD_emb       T_BE   '
           'rho_BE       M_BE    R_BE_as  scale')
    with open(out_truth, 'w') as f:
        f.write(f'# Injection truth table -- {SET_TAG}  seed={RANDOM_SEED}\n')
        f.write(f'# sep_criterion={_min_sep:.1f}"  scale_factor={SCALE_FACTOR:.4g}  '
                f'local_Sigma/SD_emb in cm-2  T_BE in K  rho_BE in cm-3  M_BE in Msun  R_BE_as in arcsec\n')
        f.write(hdr + '\n')
        f.write('#' + '-' * (len(hdr) - 1) + '\n')
        for cid, tag, xp, yp, sig, gp in truth:
            f.write(f'  {cid:03d}  {tag:12s}'
                    f'  {xp:5d}  {yp:5d}'
                    f'  {sig:11.3e}  {gp["SD_emb"]:11.3e}'
                    f'  {gp["T_BE"]:6.2f}  {gp["rho_BE"]:11.3e}'
                    f'  {gp["M_BE"]:6.4f}  {gp["R_BE_as"]:7.2f}  {SCALE_FACTOR:.4g}\n')
    print(f'  {out_truth}')

    print('Done.')


if __name__ == '__main__':
    main()
